import type { Clip } from '../clip'

// 板：鴨子在沙漠滑板場耍帥。跳起來——滑板自己溜走，一屁股坐地上；踢翻板——滑板飛上天斷成兩半，鴨子臉朝下摔。
// 蜥蜴丟來新滑板，躲在後面的蠍子一夾鴨子屁股，鴨子嚇得轉三圈，剛好穩穩落在滑板上！正要擺姿勢，蠍子跳上滑板溜走了。板、板、滑板
const clip: Clip = {
  char: '板',
  meta: { theme: '沙漠滑板場', cast: '鴨子＋蜥蜴＋蠍子', gags: ['跳起來滑板溜走', '踢翻板飛上天斷掉', '被夾一下意外成功', '滑板被蠍子騎走'] },
  duration: 10,
  bg: { top: '#FFE7C2', bottom: '#FFD08A', floor: '#E0A96D', scenery: 'desert' },
  actors: [
    { id: 'board', emoji: '🛹', x: 24, y: 73.5, size: 10, hidden: true },
    { id: 'board2', emoji: '🛹', x: 30, y: 73.5, size: 10, hidden: true },
    { id: 'scorpion', emoji: '🦂', x: 33, y: 73.6, size: 8, hidden: true, flip: true },
    { id: 'duck', emoji: '🦆', x: 24, y: 66.5, size: 12, hidden: true, flip: true },
    { id: 'lizard', emoji: '🦎', x: 144, y: 72.4, size: 11, hidden: true },
  ],
  moves: [
    { at: 0, actor: 'board', do: 'enter', from: { x: -15, y: 73.5 }, dur: 0.7 },
    { at: 0, actor: 'duck', do: 'enter', from: { x: -15, y: 66.5 }, dur: 0.7 },
    { at: 0.3, actor: 'lizard', do: 'pop' },
    // 第一招：跳——滑板自己溜走，一屁股坐地上
    { at: 1.3, actor: 'duck', do: 'squash', amount: -0.3, dur: 0.25 },
    { at: 1.55, actor: 'duck', do: 'hop', amount: 10, dur: 0.4 },
    { at: 1.55, actor: 'board', do: 'moveTo', to: { x: 46, y: 73.5 }, dur: 0.4 },
    { at: 1.95, actor: 'duck', do: 'moveTo', to: { x: 24, y: 72 }, dur: 0.1 },
    { at: 2.05, actor: 'duck', do: 'squash', amount: 0.4, dur: 0.25 },
    // 第二招：踢翻板——滑板飛上天斷掉，鴨子臉朝下
    { at: 2.6, actor: 'duck', do: 'moveTo', to: { x: 46, y: 66.5 }, arc: 4, dur: 0.4 },
    { at: 3.0, actor: 'duck', do: 'squash', amount: -0.35, dur: 0.25 },
    { at: 3.25, actor: 'duck', do: 'hop', amount: 14, dur: 0.5 },
    { at: 3.25, actor: 'duck', do: 'spin', dur: 0.5 },
    { at: 3.25, actor: 'board', do: 'moveTo', to: { x: 80, y: 30 }, arc: 6, dur: 0.5 },
    { at: 3.25, actor: 'board', do: 'spin', times: 2, dur: 0.5 },
    { at: 3.8, actor: 'board', do: 'vanish', dur: 0.1 },
    { at: 3.75, actor: 'duck', do: 'rotateTo', amount: 90, dur: 0.2 },
    { at: 3.75, actor: 'duck', do: 'moveTo', to: { x: 44, y: 65 }, dur: 0.2 },
    { at: 4.5, actor: 'duck', do: 'rotateTo', amount: -90, dur: 0.25 },
    { at: 4.5, actor: 'duck', do: 'moveTo', to: { x: 40, y: 72 }, dur: 0.25 },
    // 蜥蜴丟來新滑板
    { at: 4.8, actor: 'lizard', do: 'tilt', amount: 20, dur: 0.3 },
    { at: 4.8, actor: 'board2', do: 'enter', from: { x: 140, y: 62 }, arc: 16, dur: 0.6 },
    { at: 4.8, actor: 'board2', do: 'spin', dur: 0.6 },
    // 蠍子偷偷靠近，一夾！
    { at: 5.0, actor: 'scorpion', do: 'enter', from: { x: -12, y: 73.6 }, dur: 0.5 },
    { at: 5.6, actor: 'scorpion', do: 'squash', amount: -0.3, dur: 0.2 },
    { at: 5.65, actor: 'duck', do: 'moveTo', to: { x: 30, y: 66.5 }, arc: 32, dur: 0.85 },
    { at: 5.65, actor: 'duck', do: 'spin', times: 3, dur: 0.85 },
    { at: 6.5, actor: 'duck', do: 'squash', amount: 0.3, dur: 0.25 },
    { at: 6.5, actor: 'board2', do: 'squash', amount: 0.2, dur: 0.25 },
    // 滑來滑去
    { at: 7.3, actor: 'duck', do: 'moveTo', to: { x: 14, y: 66.5 }, dur: 0.4 },
    { at: 7.3, actor: 'board2', do: 'moveTo', to: { x: 14, y: 73.5 }, dur: 0.4 },
    { at: 7.7, actor: 'duck', do: 'moveTo', to: { x: 36, y: 66.5 }, dur: 0.4 },
    { at: 7.7, actor: 'board2', do: 'moveTo', to: { x: 36, y: 73.5 }, dur: 0.4 },
    { at: 7.7, actor: 'scorpion', do: 'moveTo', to: { x: 24, y: 73.6 }, dur: 0.4 },
    // 擺姿勢跳起來——蠍子跳上滑板溜走
    { at: 8.3, actor: 'duck', do: 'squash', amount: -0.25, dur: 0.2 },
    { at: 8.5, actor: 'duck', do: 'hop', amount: 9, dur: 0.45 },
    { at: 8.5, actor: 'scorpion', do: 'moveTo', to: { x: 36, y: 69 }, arc: 6, dur: 0.25 },
    { at: 8.75, actor: 'scorpion', do: 'flip' },
    { at: 8.75, actor: 'scorpion', do: 'moveTo', to: { x: -20, y: 69 }, dur: 0.6 },
    { at: 8.75, actor: 'board2', do: 'moveTo', to: { x: -20, y: 73.5 }, dur: 0.6 },
    { at: 8.95, actor: 'duck', do: 'moveTo', to: { x: 36, y: 72 }, dur: 0.1 },
    { at: 9.05, actor: 'duck', do: 'squash', amount: 0.4, dur: 0.25 },
    { at: 9.2, actor: 'lizard', do: 'bounce', amount: 2, times: 2, dur: 0.5 },
  ],
  builds: [
    // 斷掉的滑板 → 木；鴨子轉三圈甩出來的星星 → 反
    { at: 3.8, dur: 0.7, strokes: [0, 1, 2, 3], from: 'board', color: '#B9783B' },
    { at: 5.8, dur: 0.7, strokes: [4, 5, 6, 7], from: 'duck', color: '#1F8A9C' },
  ],
  glyph: [{ at: 4.5, dur: 0.4, do: 'wobble' }, { at: 6.5, dur: 0.4, do: 'wobble' }, { at: 9.5, dur: 0.5, do: 'pulse' }],
  fx: [
    { at: 0.7, kind: 'puff', actor: 'board' },
    { at: 0.95, kind: 'bubble', actor: 'duck', emoji: '😎', dur: 0.5 },
    { at: 2.05, kind: 'puff', actor: 'duck' },
    { at: 2.2, kind: 'sweat', actor: 'duck' },
    { at: 2.3, kind: 'pop', actor: 'lizard', emoji: '😆', dur: 0.5 },
    { at: 3.75, kind: 'burst', actor: 'board', dur: 0.4 },
    { at: 3.95, kind: 'dizzy', actor: 'duck', dy: 6, dur: 0.6 },
    { at: 4.65, kind: 'pop', actor: 'duck', emoji: '😤', dur: 0.4 },
    { at: 5.4, kind: 'pop', actor: 'scorpion', emoji: '😏', dur: 0.4 },
    { at: 5.62, kind: 'burst', actor: 'duck', dx: -6, dy: 8, dur: 0.35 },
    { at: 5.65, kind: 'pop', actor: 'duck', emoji: '😱', dur: 0.5 },
    { at: 6.5, kind: 'puff', actor: 'board2' },
    { at: 6.8, kind: 'pop', actor: 'lizard', emoji: '💯', dur: 0.7 },
    { at: 7.3, kind: 'puff', actor: 'board2' },
    { at: 8.0, kind: 'bubble', actor: 'duck', emoji: '😎', dur: 0.4 },
    { at: 9.05, kind: 'puff', actor: 'duck' },
    { at: 9.15, kind: 'dizzy', actor: 'duck', dur: 0.8 },
    { at: 9.2, kind: 'pop', actor: 'lizard', emoji: '😆', dur: 0.6 },
  ],
  camera: [
    { at: 3.75, dur: 0.3, do: 'shake', amount: 1.5 },
    { at: 6.45, dur: 0.6, do: 'punch', amount: 0.25, to: { x: 30, y: 66 } },
  ],
  cues: [
    { at: 0.1, sfx: 'slide' },
    { at: 1.5, say: '板' },
    { at: 1.55, sfx: 'slide' },
    { at: 2.05, sfx: 'bonk' },
    { at: 3.25, sfx: 'whoosh' },
    { at: 3.75, sfx: 'crack' },
    { at: 4.8, sfx: 'whoosh' },
    { at: 5.62, sfx: 'boing' },
    { at: 6.5, sfx: 'clink' },
    { at: 6.55, say: '板' },
    { at: 7.55, say: '滑板' },
    { at: 8.75, sfx: 'slide' },
    { at: 9.05, sfx: 'bonk' },
    { at: 9.6, sfx: 'cheer' },
  ],
}

export default clip
