import type { Clip } from '../clip'

// 果：倉鼠想吃樹上的蘋果，跳兩次都搆不到，靈機一動用頭撞樹——蘋果咚一聲砸在自己頭上。
// 一堆蘋果掉下來排成上面的框，樹變成「木」。最後糖果飄下來接住了，結果又一顆蘋果砸頭。果、果、糖果
const clip: Clip = {
  char: '果',
  meta: { theme: '動物', cast: '倉鼠', gags: ['搆不到', '撞樹', '東西砸頭', '回馬槍'] },
  duration: 10,
  bg: { top: '#FFE8D9', bottom: '#FFD3BF', floor: '#BFE5AE' },
  actors: [
    { id: 'tree', emoji: '🌳', x: 130, y: 55, size: 38, hidden: true },
    { id: 'pal', emoji: '🐹', x: 26, y: 71, size: 13, hidden: true },
    { id: 'apple', emoji: '🍎', x: 124, y: 44, size: 8, hidden: true },
    { id: 'r1', emoji: '🍎', x: 66, y: 72, size: 8, hidden: true },
    { id: 'r2', emoji: '🍎', x: 76, y: 72, size: 8, hidden: true },
    { id: 'r3', emoji: '🍎', x: 96, y: 72, size: 8, hidden: true },
    { id: 'r4', emoji: '🍎', x: 71, y: 65, size: 8, hidden: true },
    { id: 'r5', emoji: '🍎', x: 81, y: 65, size: 8, hidden: true },
    { id: 'candy', emoji: '🍬', x: 124, y: 58, size: 8, hidden: true },
    { id: 'again', emoji: '🍎', x: 117, y: 60, size: 8, hidden: true },
  ],
  moves: [
    { at: 0, actor: 'tree', do: 'pop', dur: 0.4 },
    { at: 0.3, actor: 'apple', do: 'pop' },
    { at: 0, actor: 'pal', do: 'enter', from: { x: -12, y: 71 }, dur: 0.7 },
    { at: 0, actor: 'pal', do: 'bounce', dur: 0.7, times: 3, amount: 2.5 },
    { at: 0.9, actor: 'pal', do: 'hop', dur: 0.3, amount: 3 },
    // 跑到樹下，跳——搆不到；再用力跳——還是搆不到
    { at: 1.5, actor: 'pal', do: 'moveTo', to: { x: 112, y: 71 }, dur: 0.55 },
    { at: 2.1, actor: 'pal', do: 'squash', amount: -0.25, dur: 0.18 },
    { at: 2.25, actor: 'pal', do: 'hop', dur: 0.45, amount: 12 },
    { at: 2.7, actor: 'pal', do: 'squash', amount: 0.3, dur: 0.15 },
    { at: 2.85, actor: 'pal', do: 'hop', dur: 0.5, amount: 16 },
    { at: 3.35, actor: 'pal', do: 'squash', amount: 0.4, dur: 0.2 },
    // 想到了：後退、蓄力、衝！
    { at: 4.0, actor: 'pal', do: 'moveTo', to: { x: 96, y: 71 }, dur: 0.3 },
    { at: 4.3, actor: 'pal', do: 'squash', amount: -0.2, dur: 0.15 },
    { at: 4.42, actor: 'pal', do: 'moveTo', to: { x: 117, y: 71 }, dur: 0.16 },
    { at: 4.58, actor: 'pal', do: 'squash', amount: 0.5, dur: 0.25 },
    { at: 4.58, actor: 'tree', do: 'shake', dur: 0.6, amount: 3 },
    // 蘋果不偏不倚砸在自己頭上
    { at: 4.65, actor: 'apple', do: 'moveTo', to: { x: 117, y: 60 }, dur: 0.3 },
    { at: 4.95, actor: 'pal', do: 'squash', amount: 0.6, dur: 0.35 },
    { at: 4.98, actor: 'apple', do: 'moveTo', to: { x: 86, y: 72 }, dur: 0.5, arc: 12 },
    { at: 5.45, actor: 'r1', do: 'enter', from: { x: 66, y: -10 }, dur: 0.4 },
    { at: 5.55, actor: 'r2', do: 'enter', from: { x: 76, y: -10 }, dur: 0.4 },
    { at: 5.65, actor: 'r3', do: 'enter', from: { x: 96, y: -10 }, dur: 0.4 },
    { at: 5.75, actor: 'r4', do: 'enter', from: { x: 71, y: -10 }, dur: 0.4 },
    { at: 5.85, actor: 'r5', do: 'enter', from: { x: 81, y: -10 }, dur: 0.4 },
    { at: 6.05, actor: 'apple', do: 'vanish' }, { at: 6.05, actor: 'r1', do: 'vanish' }, { at: 6.08, actor: 'r2', do: 'vanish' },
    { at: 6.11, actor: 'r3', do: 'vanish' }, { at: 6.14, actor: 'r4', do: 'vanish' }, { at: 6.17, actor: 'r5', do: 'vanish' },
    { at: 6.35, actor: 'tree', do: 'vanish', dur: 0.35 },
    // 糖果慢慢飄下來，跳起來一口接住
    { at: 7.2, actor: 'candy', do: 'enter', from: { x: 128, y: -8 }, dur: 0.75 },
    { at: 7.2, actor: 'candy', do: 'spin', dur: 0.75 },
    { at: 7.85, actor: 'pal', do: 'hop', dur: 0.3, amount: 6 },
    { at: 7.95, actor: 'candy', do: 'moveTo', to: { x: 117, y: 64 }, dur: 0.1 },
    { at: 8.0, actor: 'candy', do: 'vanish', dur: 0.1 },
    { at: 8.05, actor: 'pal', do: 'squash', amount: 0.3, dur: 0.3 },
    { at: 8.3, actor: 'pal', do: 'bounce', dur: 0.4, times: 2, amount: 3 },
    // 回馬槍：又一顆砸下來
    { at: 8.55, actor: 'again', do: 'enter', from: { x: 117, y: -10 }, dur: 0.35 },
    { at: 8.9, actor: 'pal', do: 'squash', amount: 0.55, dur: 0.35 },
    { at: 8.95, actor: 'again', do: 'moveTo', to: { x: 130, y: 72 }, dur: 0.45, arc: 8 },
    { at: 9.6, actor: 'again', do: 'vanish' },
  ],
  builds: [
    // 蘋果山 → 上面的框；樹 → 「木」（中間那一豎從框裡穿上去）
    { at: 6.05, dur: 0.7, strokes: [0, 1, 2, 3], from: { x: 78, y: 68 }, color: '#E0393E' },
    { at: 6.35, dur: 0.8, strokes: [4, 5, 6, 7], from: 'tree', color: '#5E9A22' },
  ],
  glyph: [{ at: 7.15, dur: 0.5, do: 'wobble' }, { at: 9.4, dur: 0.6, do: 'pulse' }],
  fx: [
    { at: 0.9, kind: 'bubble', actor: 'pal', emoji: '🍎', dur: 1.1 },
    { at: 1.5, kind: 'puff', actor: 'pal' },
    { at: 3.35, kind: 'sweat', actor: 'pal' },
    { at: 3.6, kind: 'pop', actor: 'pal', emoji: '💡', dur: 0.7 },
    { at: 4.42, kind: 'puff', actor: 'pal' },
    { at: 4.95, kind: 'burst', actor: 'pal' },
    { at: 5.0, kind: 'dizzy', actor: 'pal', dur: 1.7 },
    { at: 8.0, kind: 'burst', actor: 'pal', emoji: '❤️', n: 6 },
    { at: 8.9, kind: 'burst', actor: 'pal' },
    { at: 9.05, kind: 'bubble', actor: 'pal', emoji: '😑', dur: 0.9 },
  ],
  camera: [
    { at: 4.58, dur: 0.35, do: 'shake', amount: 1.5 },
    { at: 4.95, dur: 1.0, do: 'punch', amount: 0.35, to: { x: 117, y: 62 } },
    { at: 8.9, dur: 0.8, do: 'punch', amount: 0.3, to: { x: 117, y: 62 } },
  ],
  cues: [
    { at: 0.9, sfx: 'blip' },
    { at: 2.25, sfx: 'boing' },
    { at: 2.85, sfx: 'boing' },
    { at: 3.3, sfx: 'deflate' },
    { at: 3.6, sfx: 'blip' },
    { at: 4.42, sfx: 'whoosh' },
    { at: 4.58, sfx: 'bonk' },
    { at: 4.95, sfx: 'bonk' },
    { at: 5.0, say: '果' },
    { at: 5.6, sfx: 'plop' }, { at: 5.9, sfx: 'plop' },
    { at: 6.9, say: '果' },
    { at: 7.4, say: '糖果' },
    { at: 8.0, sfx: 'gulp' },
    { at: 8.9, sfx: 'bonk' },
    { at: 9.4, sfx: 'cheer' },
  ],
}

export default clip
