import type { Clip } from '../clip'

// 洞：浣熊玩打地鼠，地鼠總是早一步縮回去、從另一個洞冒出來，最後三隻一起探頭笑牠。浣熊拿超大槌子用力一敲，
// 三個洞被震飛變成三點水，槌子也碎成「同」；地鼠逃進樹洞，一個小洞竟然鑽出三隻——結果浣熊腳下也冒出一隻，把牠頂上天。洞、洞、樹洞
const clip: Clip = {
  char: '洞',
  meta: { theme: '打地鼠', cast: '浣熊＋三隻地鼠＋大樹', gags: ['總是慢一步', '一起探頭嘲笑', '超大槌子震飛洞', '小洞鑽出三隻', '腳下冒出來'] },
  duration: 10,
  bg: { top: '#E3F8FF', bottom: '#D2F5C4', floor: '#86C26A', scenery: 'hills' },
  actors: [
    { id: 'tree', emoji: '🌳', x: 142, y: 67, size: 24 },
    { id: 'treeHole', emoji: '🕳️', x: 142, y: 70.5, size: 6, float: true },
    { id: 'm1', emoji: '🐹', x: 56, y: 70.5, size: 10, hidden: true },
    { id: 'm2', emoji: '🐹', x: 80, y: 70.5, size: 10, hidden: true },
    { id: 'm3', emoji: '🐹', x: 104, y: 70.5, size: 10, hidden: true },
    { id: 'h1', emoji: '🕳️', x: 56, y: 74.5, size: 13, float: true, hidden: true },
    { id: 'h2', emoji: '🕳️', x: 80, y: 74.5, size: 13, float: true, hidden: true },
    { id: 'h3', emoji: '🕳️', x: 104, y: 74.5, size: 13, float: true, hidden: true },
    { id: 'm4', emoji: '🐹', x: 24, y: 70.5, size: 10, hidden: true },
    { id: 'hb', emoji: '🕳️', x: 24, y: 74.8, size: 15, float: true, hidden: true },
    { id: 'raccoon', emoji: '🦝', x: 24, y: 71.1, size: 14, hidden: true, flip: true },
    { id: 'hammer', emoji: '🔨', x: 31, y: 63, size: 9, float: true, hidden: true, flip: true },
  ],
  moves: [
    { at: 0, actor: 'raccoon', do: 'pop' },
    { at: 0.1, actor: 'hammer', do: 'pop' },
    { at: 0.15, actor: 'h1', do: 'pop' }, { at: 0.25, actor: 'h2', do: 'pop' }, { at: 0.35, actor: 'h3', do: 'pop' },
    // 第一隻冒出來，敲下去——早就縮回去了
    { at: 0.7, actor: 'm1', do: 'pop', dur: 0.2 },
    { at: 1.05, actor: 'raccoon', do: 'moveTo', to: { x: 46, y: 71.1 }, arc: 8, dur: 0.3 },
    { at: 1.05, actor: 'hammer', do: 'moveTo', to: { x: 53, y: 63 }, arc: 8, dur: 0.3 },
    { at: 1.25, actor: 'm1', do: 'vanish', dur: 0.12 },
    { at: 1.35, actor: 'hammer', do: 'tilt', amount: -70, dur: 0.25 },
    { at: 1.35, actor: 'raccoon', do: 'squash', amount: 0.2, dur: 0.2 },
    { at: 1.5, actor: 'm3', do: 'pop', dur: 0.2 },
    // 跳到第三個洞——又縮回去，換兩隻冒出來
    { at: 2.1, actor: 'raccoon', do: 'moveTo', to: { x: 92, y: 71.1 }, arc: 12, dur: 0.35 },
    { at: 2.1, actor: 'hammer', do: 'moveTo', to: { x: 99, y: 63 }, arc: 12, dur: 0.35 },
    { at: 2.35, actor: 'm3', do: 'vanish', dur: 0.12 },
    { at: 2.45, actor: 'hammer', do: 'tilt', amount: -70, dur: 0.25 },
    { at: 2.45, actor: 'raccoon', do: 'squash', amount: 0.2, dur: 0.2 },
    { at: 2.55, actor: 'm1', do: 'pop', dur: 0.2 },
    { at: 2.6, actor: 'm2', do: 'pop', dur: 0.2 },
    // 敲中間——全部縮回去，再三隻一起探頭嘲笑
    { at: 3.0, actor: 'raccoon', do: 'moveTo', to: { x: 70, y: 71.1 }, arc: 10, dur: 0.3 },
    { at: 3.0, actor: 'hammer', do: 'moveTo', to: { x: 77, y: 63 }, arc: 10, dur: 0.3 },
    { at: 3.2, actor: 'm1', do: 'vanish', dur: 0.12 },
    { at: 3.2, actor: 'm2', do: 'vanish', dur: 0.12 },
    { at: 3.3, actor: 'hammer', do: 'tilt', amount: -70, dur: 0.25 },
    { at: 3.3, actor: 'raccoon', do: 'squash', amount: 0.2, dur: 0.2 },
    { at: 3.5, actor: 'm1', do: 'pop', dur: 0.2 },
    { at: 3.55, actor: 'm2', do: 'pop', dur: 0.2 },
    { at: 3.6, actor: 'm3', do: 'pop', dur: 0.2 },
    { at: 3.75, actor: 'm1', do: 'bounce', amount: 2, times: 3, dur: 0.6 },
    { at: 3.75, actor: 'm2', do: 'bounce', amount: 2, times: 3, dur: 0.6 },
    { at: 3.75, actor: 'm3', do: 'bounce', amount: 2, times: 3, dur: 0.6 },
    { at: 3.8, actor: 'raccoon', do: 'shake', amount: 1.5, dur: 0.4 },
    // 槌子變超大，跳起來用力一敲
    { at: 4.2, actor: 'hammer', do: 'scaleTo', amount: 2, dur: 0.3 },
    { at: 4.2, actor: 'raccoon', do: 'squash', amount: -0.35, dur: 0.3 },
    { at: 4.45, actor: 'raccoon', do: 'hop', amount: 16, dur: 0.5 },
    { at: 4.45, actor: 'hammer', do: 'hop', amount: 16, dur: 0.5 },
    { at: 4.85, actor: 'hammer', do: 'tilt', amount: -90, dur: 0.25 },
    { at: 4.9, actor: 'raccoon', do: 'squash', amount: 0.4, dur: 0.3 },
    // 洞被震飛；地鼠沒地方躲，逃進樹裡
    { at: 5.0, actor: 'h1', do: 'vanish', dur: 0.2 }, { at: 5.0, actor: 'h2', do: 'vanish', dur: 0.2 }, { at: 5.0, actor: 'h3', do: 'vanish', dur: 0.2 },
    { at: 5.0, actor: 'm1', do: 'hop', amount: 8, dur: 0.35 },
    { at: 5.0, actor: 'm2', do: 'hop', amount: 8, dur: 0.35 },
    { at: 5.0, actor: 'm3', do: 'hop', amount: 8, dur: 0.35 },
    { at: 5.45, actor: 'm3', do: 'moveTo', to: { x: 142, y: 70 }, dur: 0.3 },
    { at: 5.5, actor: 'm2', do: 'moveTo', to: { x: 142, y: 70 }, dur: 0.35 },
    { at: 5.55, actor: 'm1', do: 'moveTo', to: { x: 142, y: 70 }, dur: 0.4 },
    { at: 5.75, actor: 'm3', do: 'vanish', dur: 0.1 },
    { at: 5.85, actor: 'm2', do: 'vanish', dur: 0.1 },
    { at: 5.95, actor: 'm1', do: 'vanish', dur: 0.1 },
    // 浣熊被反彈回去，槌子碎掉
    { at: 5.05, actor: 'raccoon', do: 'moveTo', to: { x: 24, y: 71.1 }, arc: 14, dur: 0.5 },
    { at: 5.05, actor: 'raccoon', do: 'spin', dur: 0.5 },
    { at: 5.4, actor: 'hammer', do: 'vanish', dur: 0.2 },
    // 樹上的小洞，一隻、兩隻、三隻
    { at: 6.2, actor: 'm1', do: 'moveTo', to: { x: 142, y: 66 }, dur: 0.01 },
    { at: 6.2, actor: 'm2', do: 'moveTo', to: { x: 142, y: 58 }, dur: 0.01 },
    { at: 6.2, actor: 'm3', do: 'moveTo', to: { x: 142, y: 50 }, dur: 0.01 },
    { at: 7.2, actor: 'm1', do: 'pop', dur: 0.2 },
    { at: 7.6, actor: 'm2', do: 'pop', dur: 0.2 },
    { at: 8.0, actor: 'm3', do: 'pop', dur: 0.2 },
    // 回馬槍：浣熊腳下冒出一個洞，地鼠把牠頂上去
    { at: 8.45, actor: 'hb', do: 'pop', dur: 0.2 },
    { at: 8.55, actor: 'raccoon', do: 'shake', amount: 0.8, dur: 0.3 },
    { at: 8.9, actor: 'm4', do: 'pop', dur: 0.2 },
    { at: 8.9, actor: 'raccoon', do: 'moveTo', to: { x: 24, y: 61 }, dur: 0.2 },
    { at: 9.1, actor: 'm1', do: 'bounce', amount: 1.5, times: 3, dur: 0.6 },
    { at: 9.1, actor: 'm2', do: 'bounce', amount: 1.5, times: 3, dur: 0.6 },
    { at: 9.1, actor: 'm3', do: 'bounce', amount: 1.5, times: 3, dur: 0.6 },
  ],
  builds: [
    // 震飛的三個洞 → 三點水；碎掉的槌子 → 同
    { at: 4.95, dur: 0.6, strokes: [0, 1, 2], from: 'h2', color: '#5B3A29' },
    { at: 5.4, dur: 0.8, strokes: [3, 4, 5, 6, 7, 8], from: 'hammer', color: '#00897B' },
  ],
  glyph: [{ at: 6.2, dur: 0.4, do: 'wobble' }, { at: 9.5, dur: 0.5, do: 'pulse' }],
  fx: [
    { at: 0.8, kind: 'pop', actor: 'm1', emoji: '😜', dur: 0.5 },
    { at: 0.9, kind: 'pop', actor: 'raccoon', emoji: '❗', dur: 0.4 },
    { at: 1.45, kind: 'burst', x: 56, y: 70, emoji: '💨', n: 5, dur: 0.4 },
    { at: 1.6, kind: 'pop', actor: 'm3', emoji: '😜', dur: 0.5 },
    { at: 2.55, kind: 'burst', x: 104, y: 70, emoji: '💨', n: 5, dur: 0.4 },
    { at: 2.7, kind: 'sweat', actor: 'raccoon' },
    { at: 3.4, kind: 'burst', x: 80, y: 70, emoji: '💨', n: 5, dur: 0.4 },
    { at: 3.65, kind: 'pop', actor: 'm1', emoji: '😆', dur: 0.6 },
    { at: 3.65, kind: 'pop', actor: 'm2', emoji: '😆', dur: 0.6 },
    { at: 3.65, kind: 'pop', actor: 'm3', emoji: '😆', dur: 0.6 },
    { at: 3.85, kind: 'pop', actor: 'raccoon', emoji: '💢', dur: 0.5 },
    { at: 4.9, kind: 'burst', x: 80, y: 66, dur: 0.5 },
    { at: 5.05, kind: 'pop', actor: 'm2', emoji: '😳', dur: 0.4 },
    { at: 5.35, kind: 'burst', actor: 'hammer', emoji: '✨', n: 6, dur: 0.5 },
    { at: 5.6, kind: 'dizzy', actor: 'raccoon', dur: 1.0 },
    { at: 6.8, kind: 'pop', actor: 'raccoon', emoji: '❓', dur: 0.6 },
    { at: 7.3, kind: 'pop', actor: 'm1', emoji: '😜', dur: 0.4, dx: -12 },
    { at: 8.1, kind: 'pop', actor: 'raccoon', emoji: '😑', dur: 0.5 },
    { at: 9.0, kind: 'pop', actor: 'raccoon', emoji: '😳', dur: 0.8 },
    { at: 9.1, kind: 'pop', actor: 'm3', emoji: '😆', dur: 0.7, dx: -14 },
  ],
  camera: [
    { at: 3.6, dur: 0.7, do: 'punch', amount: 0.25, to: { x: 80, y: 66 } },
    { at: 4.9, dur: 0.5, do: 'shake', amount: 2.5 },
  ],
  cues: [
    { at: 0.7, sfx: 'blip' },
    { at: 1.45, sfx: 'tap' },
    { at: 1.5, say: '洞' },
    { at: 2.55, sfx: 'tap' },
    { at: 3.4, sfx: 'tap' },
    { at: 4.2, sfx: 'boing' },
    { at: 4.9, sfx: 'bonk' },
    { at: 4.95, sfx: 'rumble' },
    { at: 5.35, sfx: 'crack' },
    { at: 5.45, sfx: 'whoosh' },
    { at: 6.25, say: '洞' },
    { at: 7.2, sfx: 'plop' },
    { at: 7.25, say: '樹洞' },
    { at: 7.6, sfx: 'plop' },
    { at: 8.0, sfx: 'plop' },
    { at: 8.9, sfx: 'boing' },
    { at: 9.6, sfx: 'cheer' },
  ],
}

export default clip
