import type { Clip } from '../clip'

// 灰：大掃除！掃地機器人吸灰塵、吸襪子，越吸越貪心，連睡覺的貓都吸進去，脹到「碰」一聲爆開，吐出一團灰變成「灰」。
// 貓咪被噴得全身灰撲撲，用力一抖抖出一大團灰塵；牠一巴掌把灰塵拍到機器人臉上，機器人打了一個超大噴嚏轉圈圈。灰、灰、灰塵
const clip: Clip = {
  char: '灰',
  meta: { theme: '大掃除', cast: '掃地機器人＋貓', gags: ['什麼都吸（失控）', '連貓都吸進去', '灰撲撲的貓抖出灰塵', '機器人打噴嚏'] },
  duration: 10,
  bg: { top: '#F3EEFF', bottom: '#DDD3FF', floor: '#B98C64', scenery: 'room' },
  actors: [
    { id: 'dust1', emoji: '🌫️', x: 50, y: 72.8, size: 10, tint: 'brightness(.7)' },
    { id: 'dust2', emoji: '🌫️', x: 68, y: 72.8, size: 10, tint: 'brightness(.7)' },
    { id: 'sock', emoji: '🧦', x: 88, y: 74, size: 7 },
    { id: 'cat', emoji: '🐈', x: 130, y: 71.5, size: 13 },
    { id: 'grayCat', emoji: '🐈', x: 26, y: 71.5, size: 13, hidden: true, tint: 'grayscale(1) brightness(.72)' },
    { id: 'cat2', emoji: '🐈', x: 26, y: 71.5, size: 13, hidden: true },
    { id: 'dustBall', emoji: '🌫️', x: 30, y: 62, size: 9, hidden: true, float: true, tint: 'brightness(.7)' },
    { id: 'robot', emoji: '🤖', x: 20, y: 72, size: 12, hidden: true },
  ],
  moves: [
    { at: 0, actor: 'robot', do: 'pop' },
    { at: 0.3, actor: 'robot', do: 'flash', dur: 0.5 },
    // 吸灰塵
    { at: 1.0, actor: 'dust1', do: 'moveTo', to: { x: 24, y: 72 }, dur: 0.3 },
    { at: 1.2, actor: 'dust1', do: 'vanish', dur: 0.15 },
    { at: 1.35, actor: 'robot', do: 'squash', amount: 0.25, dur: 0.25 },
    { at: 1.8, actor: 'robot', do: 'moveTo', to: { x: 46, y: 72 }, dur: 0.4 },
    { at: 2.2, actor: 'dust2', do: 'moveTo', to: { x: 50, y: 72 }, dur: 0.25 },
    { at: 2.35, actor: 'dust2', do: 'vanish', dur: 0.15 },
    { at: 2.5, actor: 'robot', do: 'squash', amount: 0.25, dur: 0.25 },
    // 吸襪子
    { at: 2.6, actor: 'robot', do: 'moveTo', to: { x: 72, y: 72 }, dur: 0.3 },
    { at: 2.9, actor: 'sock', do: 'moveTo', to: { x: 76, y: 72 }, dur: 0.2 },
    { at: 3.0, actor: 'sock', do: 'vanish', dur: 0.15 },
    { at: 3.15, actor: 'robot', do: 'scaleTo', amount: 1.15, dur: 0.2 },
    // 連貓都吸進去
    { at: 3.4, actor: 'robot', do: 'moveTo', to: { x: 100, y: 72 }, dur: 0.4 },
    { at: 3.9, actor: 'cat', do: 'moveTo', to: { x: 110, y: 71.5 }, dur: 0.4 },
    { at: 4.1, actor: 'cat', do: 'squash', amount: -0.45, dur: 0.3 },
    { at: 4.3, actor: 'cat', do: 'moveTo', to: { x: 102, y: 71.5 }, dur: 0.12 },
    { at: 4.35, actor: 'cat', do: 'vanish', dur: 0.12 },
    { at: 4.45, actor: 'robot', do: 'scaleTo', amount: 1.3, dur: 0.2 },
    // 脹到爆開
    { at: 4.6, actor: 'robot', do: 'shake', amount: 2, dur: 0.6 },
    { at: 4.6, actor: 'robot', do: 'flash', dur: 0.6 },
    { at: 5.2, actor: 'robot', do: 'moveTo', to: { x: 140, y: 72 }, arc: 15, dur: 0.5 },
    { at: 5.2, actor: 'robot', do: 'spin', times: 2, dur: 0.5 },
    { at: 5.2, actor: 'robot', do: 'scaleTo', amount: 0.67, dur: 0.3 },
    { at: 5.25, actor: 'grayCat', do: 'enter', from: { x: 100, y: 62 }, arc: 20, dur: 0.6 },
    { at: 5.85, actor: 'grayCat', do: 'squash', amount: 0.3, dur: 0.3 },
    // 用力一抖：抖出一大團灰塵
    { at: 6.9, actor: 'grayCat', do: 'shake', amount: 2, dur: 0.5 },
    { at: 7.3, actor: 'grayCat', do: 'vanish', dur: 0.1 },
    { at: 7.3, actor: 'cat2', do: 'pop', dur: 0.15 },
    { at: 7.3, actor: 'dustBall', do: 'pop', dur: 0.3 },
    { at: 7.6, actor: 'dustBall', do: 'bounce', amount: 1.5, times: 2, dur: 0.7 },
    // 一巴掌拍到機器人臉上，哈啾！
    { at: 8.2, actor: 'cat2', do: 'squash', amount: -0.25, dur: 0.25 },
    { at: 8.3, actor: 'cat2', do: 'tilt', amount: 20, dur: 0.3 },
    { at: 8.4, actor: 'dustBall', do: 'moveTo', to: { x: 140, y: 66 }, arc: 45, dur: 0.45 },
    { at: 8.85, actor: 'dustBall', do: 'vanish', dur: 0.1 },
    { at: 8.85, actor: 'robot', do: 'squash', amount: -0.3, dur: 0.2 },
    { at: 9.05, actor: 'robot', do: 'hop', amount: 8, dur: 0.45 },
    { at: 9.05, actor: 'robot', do: 'spin', times: 2, dur: 0.45 },
    { at: 9.2, actor: 'cat2', do: 'bounce', amount: 2, times: 3, dur: 0.7 },
  ],
  builds: [
    // 爆開的灰塵 → 厂；機器人冒出的火花 → 火
    { at: 5.2, dur: 0.5, strokes: [0, 1], from: 'robot', color: '#7D7F8C' },
    { at: 5.5, dur: 0.8, strokes: [2, 3, 4, 5], from: 'robot', color: '#FF7A2F' },
  ],
  glyph: [{ at: 6.3, dur: 0.4, do: 'wobble' }, { at: 9.5, dur: 0.5, do: 'pulse' }],
  fx: [
    { at: 0.2, kind: 'zzz', actor: 'cat', dur: 3.6 },
    { at: 0.5, kind: 'bubble', actor: 'robot', emoji: '🧹', dur: 0.5 },
    { at: 0.95, kind: 'line', actor: 'robot', target: 'dust1', color: '#C9CCF5', width: 2, dur: 0.35 },
    { at: 2.15, kind: 'line', actor: 'robot', target: 'dust2', color: '#C9CCF5', width: 2, dur: 0.3 },
    { at: 2.85, kind: 'line', actor: 'robot', target: 'sock', color: '#C9CCF5', width: 2, dur: 0.25 },
    { at: 3.25, kind: 'pop', actor: 'robot', emoji: '😋', dur: 0.4 },
    { at: 3.85, kind: 'line', actor: 'robot', target: 'cat', color: '#C9CCF5', width: 2.5, dur: 0.55 },
    { at: 3.95, kind: 'pop', actor: 'cat', emoji: '😱', dur: 0.4 },
    { at: 5.2, kind: 'burst', actor: 'robot', emoji: '🌫️', n: 8, dur: 0.6 },
    { at: 5.5, kind: 'burst', actor: 'robot', emoji: '⚡', n: 5, dur: 0.5 },
    { at: 5.9, kind: 'dizzy', actor: 'grayCat', dur: 0.9 },
    { at: 6.6, kind: 'pop', actor: 'grayCat', emoji: '😾', dur: 0.4 },
    { at: 7.1, kind: 'burst', actor: 'grayCat', emoji: '💨', n: 6, dur: 0.5 },
    { at: 7.6, kind: 'pop', actor: 'cat2', emoji: '😤', dur: 0.5 },
    { at: 9.05, kind: 'burst', actor: 'robot', emoji: '💦', n: 6, dur: 0.5 },
    { at: 9.2, kind: 'pop', actor: 'cat2', emoji: '😹', dur: 0.8 },
  ],
  camera: [
    { at: 4.6, dur: 0.7, do: 'punch', amount: 0.25, to: { x: 100, y: 64 } },
    { at: 5.2, dur: 0.4, do: 'shake', amount: 2 },
  ],
  cues: [
    { at: 1.0, sfx: 'whoosh' },
    { at: 1.4, say: '灰' },
    { at: 2.2, sfx: 'whoosh' },
    { at: 2.5, sfx: 'gulp' },
    { at: 2.9, sfx: 'whoosh' },
    { at: 3.1, sfx: 'gulp' },
    { at: 3.9, sfx: 'whoosh' },
    { at: 4.4, sfx: 'gulp' },
    { at: 5.2, sfx: 'crack' },
    { at: 5.25, sfx: 'poof' },
    { at: 6.35, say: '灰' },
    { at: 7.1, sfx: 'poof' },
    { at: 7.35, say: '灰塵' },
    { at: 8.4, sfx: 'whoosh' },
    { at: 9.05, sfx: 'achoo' },
    { at: 9.6, sfx: 'cheer' },
  ],
}

export default clip
