import type { Clip } from '../clip'

// 燈：小雞在十字路口等過馬路。綠燈了，小雞左看右看太久又變紅燈，汽車咻地衝過去把牠吹得轉圈；第二次綠燈一秒就變紅，大卡車又衝過。
// 小雞氣到瞪紅綠燈，燈緊張到亂閃、紅黃綠燈全彈出來變成「燈」。小雞換上一顆電燈泡——一亮，竟然又是紅的。燈、燈、電燈
const clip: Clip = {
  char: '燈',
  meta: { theme: '十字路口紅綠燈', cast: '小雞＋紅綠燈＋汽車', gags: ['猶豫太久', '一秒就變紅', '被瞪到緊張亂閃', '換了燈泡還是紅'] },
  duration: 10,
  bg: { top: '#1A2142', bottom: '#3E4374', floor: '#55566A', scenery: 'night' },
  actors: [
    { id: 'light', emoji: '🚦', x: 132, y: 67, size: 24, hidden: true },
    { id: 'sig', emoji: '🔴', x: 132, y: 45, size: 8, hidden: true, float: true },
    { id: 'bulb', emoji: '💡', x: 132, y: 48, size: 9, hidden: true, float: true },
    { id: 'chick', emoji: '🐥', x: 30, y: 73.2, size: 9, hidden: true },
    { id: 'car', emoji: '🚗', x: 70, y: 62, size: 34, hidden: true, float: true },
    { id: 'truck', emoji: '🚚', x: 70, y: 56, size: 46, hidden: true, float: true },
  ],
  moves: [
    { at: 0, actor: 'light', do: 'pop' },
    { at: 0.3, actor: 'sig', do: 'pop' },
    { at: 0, actor: 'chick', do: 'enter', from: { x: -10, y: 73.2 }, dur: 0.6 },
    // 綠燈：左看右看太久
    { at: 1.4, actor: 'sig', do: 'swap', emoji: '🟢' },
    { at: 1.4, actor: 'sig', do: 'flash', dur: 0.4 },
    { at: 1.65, actor: 'chick', do: 'tilt', amount: 18, dur: 0.3 },
    { at: 1.95, actor: 'chick', do: 'tilt', amount: -18, dur: 0.3 },
    { at: 2.3, actor: 'sig', do: 'swap', emoji: '🟡' },
    { at: 2.4, actor: 'chick', do: 'moveTo', to: { x: 40, y: 73.2 }, dur: 0.15 },
    { at: 2.5, actor: 'sig', do: 'swap', emoji: '🔴' },
    // 汽車咻地衝過
    { at: 2.6, actor: 'car', do: 'pop', dur: 0.1 },
    { at: 2.65, actor: 'car', do: 'moveTo', to: { x: 215, y: 62 }, dur: 0.3 },
    { at: 2.95, actor: 'car', do: 'vanish', dur: 0.05 },
    { at: 2.65, actor: 'chick', do: 'spin', times: 2, dur: 0.5 },
    { at: 2.65, actor: 'chick', do: 'moveTo', to: { x: 26, y: 73.2 }, dur: 0.5 },
    // 第二次：一秒就變紅
    { at: 3.5, actor: 'sig', do: 'swap', emoji: '🟢' },
    { at: 3.5, actor: 'chick', do: 'squash', amount: -0.35, dur: 0.15 },
    { at: 3.6, actor: 'chick', do: 'moveTo', to: { x: 60, y: 73.2 }, dur: 0.22 },
    { at: 3.72, actor: 'sig', do: 'swap', emoji: '🔴' },
    { at: 3.85, actor: 'chick', do: 'moveTo', to: { x: 28, y: 73.2 }, dur: 0.3 },
    { at: 4.0, actor: 'truck', do: 'pop', dur: 0.1 },
    { at: 4.05, actor: 'truck', do: 'moveTo', to: { x: 225, y: 56 }, dur: 0.35 },
    { at: 4.4, actor: 'truck', do: 'vanish', dur: 0.05 },
    // 瞪紅綠燈：燈緊張到亂閃
    { at: 4.5, actor: 'chick', do: 'bounce', dur: 0.5, times: 2, amount: 2 },
    { at: 4.7, actor: 'sig', do: 'swap', emoji: '🟢' },
    { at: 4.78, actor: 'sig', do: 'swap', emoji: '🟡' },
    { at: 4.86, actor: 'sig', do: 'swap', emoji: '🔴' },
    { at: 4.94, actor: 'sig', do: 'swap', emoji: '🟢' },
    { at: 5.02, actor: 'sig', do: 'swap', emoji: '🟡' },
    { at: 5.1, actor: 'sig', do: 'swap', emoji: '🔴' },
    { at: 4.7, actor: 'light', do: 'shake', amount: 2, dur: 0.6 },
    { at: 4.7, actor: 'light', do: 'flash', dur: 0.6 },
    { at: 5.2, actor: 'sig', do: 'vanish', dur: 0.15 },
    { at: 5.3, actor: 'light', do: 'rotateTo', amount: 12, dur: 0.3 },
    // 換上電燈泡
    { at: 7.1, actor: 'bulb', do: 'drop', dur: 0.6 },
    { at: 7.7, actor: 'bulb', do: 'flash', dur: 0.6 },
    // 一亮，竟然又是紅的
    { at: 8.3, actor: 'chick', do: 'moveTo', to: { x: 40, y: 73.2 }, dur: 0.3, arc: 2 },
    { at: 8.6, actor: 'bulb', do: 'swap', emoji: '🔴' },
    { at: 8.6, actor: 'bulb', do: 'scaleTo', amount: 0.9, dur: 0.1 },
    { at: 8.65, actor: 'chick', do: 'squash', amount: -0.25, dur: 0.3 },
    { at: 9.2, actor: 'chick', do: 'moveTo', to: { x: 30, y: 73.2 }, dur: 0.3 },
  ],
  builds: [
    // 紅、黃、綠燈全部彈出來
    { at: 5.2, dur: 0.5, strokes: [0, 1, 2, 3], from: 'light', color: '#FF4B4B' },
    { at: 5.5, dur: 0.6, strokes: [4, 5, 6, 7, 8], from: 'light', color: '#FFC21A' },
    { at: 5.8, dur: 0.8, strokes: [9, 10, 11, 12, 13, 14, 15], from: 'light', color: '#35C759' },
  ],
  glyph: [{ at: 6.7, dur: 0.4, do: 'wobble' }, { at: 9.5, dur: 0.5, do: 'pulse' }],
  fx: [
    { at: 0.7, kind: 'bubble', actor: 'chick', emoji: '🏫', dur: 0.6 },
    { at: 2.3, kind: 'pop', actor: 'chick', emoji: '❗', dur: 0.35 },
    { at: 2.65, kind: 'burst', actor: 'chick', emoji: '🪶', n: 5, dur: 0.5 },
    { at: 3.15, kind: 'bubble', actor: 'chick', emoji: '😑', dur: 0.35 },
    { at: 3.9, kind: 'puff', actor: 'chick' },
    { at: 4.1, kind: 'sweat', actor: 'chick' },
    { at: 4.45, kind: 'pop', actor: 'chick', emoji: '💢', dur: 0.5 },
    { at: 4.7, kind: 'sweat', actor: 'light', dx: -8 },
    { at: 5.2, kind: 'burst', actor: 'light', emoji: '🔴', n: 3, dur: 0.5 },
    { at: 5.3, kind: 'burst', actor: 'light', emoji: '🟡', n: 3, dur: 0.5 },
    { at: 5.4, kind: 'burst', actor: 'light', emoji: '🟢', n: 3, dur: 0.5 },
    { at: 5.6, kind: 'dizzy', actor: 'light', dur: 1.0 },
    { at: 7.0, kind: 'pop', actor: 'chick', emoji: '💡', dur: 0.5 },
    { at: 7.7, kind: 'burst', actor: 'bulb', emoji: '✨', n: 6, dur: 0.6 },
    { at: 8.7, kind: 'pop', actor: 'chick', emoji: '❗', dur: 0.4 },
    { at: 9.1, kind: 'bubble', actor: 'chick', emoji: '😑', dur: 0.8 },
  ],
  camera: [
    { at: 2.65, dur: 0.35, do: 'shake', amount: 1.5 },
    { at: 4.05, dur: 0.4, do: 'shake', amount: 2 },
    { at: 8.6, dur: 0.7, do: 'punch', amount: 0.2, to: { x: 60, y: 60 } },
  ],
  cues: [
    { at: 1.4, sfx: 'blip' },
    { at: 1.5, say: '燈' },
    { at: 2.65, sfx: 'whoosh' },
    { at: 3.5, sfx: 'blip' },
    { at: 3.72, sfx: 'blip' },
    { at: 3.85, sfx: 'slide' },
    { at: 4.05, sfx: 'whoosh' },
    { at: 4.7, sfx: 'blip' }, { at: 4.86, sfx: 'blip' }, { at: 5.02, sfx: 'blip' },
    { at: 5.2, sfx: 'poof' },
    { at: 6.7, say: '燈' },
    { at: 7.6, sfx: 'clink' },
    { at: 7.7, say: '電燈' },
    { at: 8.6, sfx: 'blip' },
    { at: 9.6, sfx: 'cheer' },
  ],
}

export default clip
