import type { Clip } from '../clip'

// 糕：小豬生日吹蠟燭，吹熄了又自己點起來；鼓起臉再吹，又點起來；氣到鼓成一顆大氣球用力一吹——
// 火苗飛上天掉成「灬」、蛋糕被吹到對面、奶油飛成「羊」，小豬像洩氣的氣球滿天亂飛；章魚拉炮噴出「米」。蠟燭又點起來，章魚一口把蛋糕吞掉，打嗝噴出一朵小火。糕、糕、蛋糕
const clip: Clip = {
  char: '糕',
  meta: { theme: '生日派對', cast: '小豬＋章魚＋魔術蠟燭蛋糕', gags: ['吹熄又點起來', '越鼓越大', '洩氣滿天飛', '一口吞掉打嗝噴火'] },
  duration: 10,
  bg: { top: '#FFF0F6', bottom: '#FFE1EC', floor: '#C98E6B', scenery: 'room' },
  actors: [
    { id: 'cake', emoji: '🎂', x: 80, y: 69.4, size: 18 },
    { id: 'f1', emoji: '🔥', x: 75, y: 59.5, size: 4, float: true, hidden: true },
    { id: 'f2', emoji: '🔥', x: 78.5, y: 59, size: 4, float: true, hidden: true },
    { id: 'f3', emoji: '🔥', x: 82, y: 59, size: 4, float: true, hidden: true },
    { id: 'f4', emoji: '🔥', x: 85.5, y: 59.5, size: 4, float: true, hidden: true },
    { id: 'f5', emoji: '🔥', x: 114, y: 59, size: 4, float: true, hidden: true },
    { id: 'octopus', emoji: '🐙', x: 136, y: 71.5, size: 13, hidden: true },
    { id: 'popper', emoji: '🎉', x: 127, y: 63, size: 7, float: true, hidden: true },
    { id: 'pig', emoji: '🐷', x: 30, y: 71.1, size: 14, hidden: true, flip: true },
    { id: 'g1', emoji: '💨', x: 44, y: 64, size: 7, float: true, hidden: true, flip: true },
    { id: 'g2', emoji: '💨', x: 46, y: 63, size: 10, float: true, hidden: true, flip: true },
    { id: 'g3', emoji: '💨', x: 50, y: 62, size: 18, float: true, hidden: true, flip: true },
  ],
  moves: [
    { at: 0, actor: 'pig', do: 'enter', from: { x: -12, y: 71.1 }, dur: 0.5 },
    { at: 0.2, actor: 'f1', do: 'pop', dur: 0.2 }, { at: 0.25, actor: 'f2', do: 'pop', dur: 0.2 },
    { at: 0.3, actor: 'f3', do: 'pop', dur: 0.2 }, { at: 0.35, actor: 'f4', do: 'pop', dur: 0.2 },
    { at: 0.3, actor: 'octopus', do: 'pop' },
    { at: 0.45, actor: 'popper', do: 'pop' },
    // 第一次吹：熄了……又點起來
    { at: 1.0, actor: 'pig', do: 'squash', amount: -0.2, dur: 0.35 },
    { at: 1.35, actor: 'g1', do: 'pop', dur: 0.05 },
    { at: 1.35, actor: 'g1', do: 'moveTo', to: { x: 72, y: 61 }, dur: 0.25 },
    { at: 1.6, actor: 'g1', do: 'vanish', dur: 0.1 },
    { at: 1.55, actor: 'f1', do: 'vanish', dur: 0.1 }, { at: 1.55, actor: 'f2', do: 'vanish', dur: 0.1 },
    { at: 1.55, actor: 'f3', do: 'vanish', dur: 0.1 }, { at: 1.55, actor: 'f4', do: 'vanish', dur: 0.1 },
    { at: 2.0, actor: 'f1', do: 'pop', dur: 0.2 }, { at: 2.05, actor: 'f2', do: 'pop', dur: 0.2 },
    { at: 2.1, actor: 'f3', do: 'pop', dur: 0.2 }, { at: 2.15, actor: 'f4', do: 'pop', dur: 0.2 },
    // 鼓起臉再吹：又點起來
    { at: 2.6, actor: 'pig', do: 'scaleTo', amount: 1.35, dur: 0.4 },
    { at: 3.05, actor: 'g2', do: 'pop', dur: 0.05 },
    { at: 3.05, actor: 'g2', do: 'moveTo', to: { x: 72, y: 61 }, dur: 0.2 },
    { at: 3.05, actor: 'pig', do: 'scaleTo', amount: 1 / 1.35, dur: 0.25 },
    { at: 3.25, actor: 'g2', do: 'vanish', dur: 0.1 },
    { at: 3.2, actor: 'f1', do: 'vanish', dur: 0.1 }, { at: 3.2, actor: 'f2', do: 'vanish', dur: 0.1 },
    { at: 3.2, actor: 'f3', do: 'vanish', dur: 0.1 }, { at: 3.2, actor: 'f4', do: 'vanish', dur: 0.1 },
    { at: 3.6, actor: 'f1', do: 'pop', dur: 0.2 }, { at: 3.65, actor: 'f2', do: 'pop', dur: 0.2 },
    { at: 3.7, actor: 'f3', do: 'pop', dur: 0.2 }, { at: 3.75, actor: 'f4', do: 'pop', dur: 0.2 },
    { at: 3.75, actor: 'pig', do: 'shake', amount: 1.5, dur: 0.4 },
    { at: 3.8, actor: 'octopus', do: 'bounce', amount: 2, times: 3, dur: 0.6 },
    // 氣到鼓成大氣球：超級一吹
    { at: 4.1, actor: 'pig', do: 'scaleTo', amount: 1.9, dur: 0.6 },
    { at: 4.75, actor: 'g3', do: 'pop', dur: 0.05 },
    { at: 4.75, actor: 'g3', do: 'moveTo', to: { x: 84, y: 60 }, dur: 0.2 },
    { at: 5.0, actor: 'g3', do: 'vanish', dur: 0.15 },
    { at: 4.85, actor: 'f1', do: 'vanish', dur: 0.05 }, { at: 4.85, actor: 'f2', do: 'vanish', dur: 0.05 },
    { at: 4.85, actor: 'f3', do: 'vanish', dur: 0.05 }, { at: 4.85, actor: 'f4', do: 'vanish', dur: 0.05 },
    { at: 4.9, actor: 'cake', do: 'moveTo', to: { x: 114, y: 69.4 }, dur: 0.35 },
    // 洩氣的氣球：滿天亂飛
    { at: 4.8, actor: 'pig', do: 'scaleTo', amount: 1 / 1.9, dur: 0.7 },
    { at: 4.8, actor: 'pig', do: 'moveTo', to: { x: 14, y: 58 }, dur: 0.25 },
    { at: 5.05, actor: 'pig', do: 'moveTo', to: { x: 36, y: 46 }, dur: 0.25 },
    { at: 5.3, actor: 'pig', do: 'moveTo', to: { x: 30, y: 71.1 }, dur: 0.3 },
    { at: 4.8, actor: 'pig', do: 'spin', times: 2, dur: 0.8 },
    { at: 5.6, actor: 'pig', do: 'squash', amount: 0.3, dur: 0.25 },
    // 終於熄了！章魚拉炮
    { at: 5.55, actor: 'octopus', do: 'hop', amount: 4, dur: 0.3 },
    { at: 5.6, actor: 'popper', do: 'flash', dur: 0.4 },
    { at: 6.4, actor: 'popper', do: 'vanish', dur: 0.25 },
    // 蛋糕！
    { at: 6.9, actor: 'cake', do: 'bounce', amount: 3, times: 2, dur: 0.5 },
    { at: 7.2, actor: 'cake', do: 'flash', dur: 0.5 },
    // 回馬槍：蠟燭又點起來，章魚一口吞掉
    { at: 8.0, actor: 'f5', do: 'pop', dur: 0.2 },
    { at: 8.5, actor: 'octopus', do: 'squash', amount: -0.25, dur: 0.25 },
    { at: 8.75, actor: 'octopus', do: 'moveTo', to: { x: 125, y: 71.5 }, dur: 0.15 },
    { at: 8.8, actor: 'cake', do: 'vanish', dur: 0.1 },
    { at: 8.8, actor: 'f5', do: 'vanish', dur: 0.1 },
    { at: 8.9, actor: 'octopus', do: 'squash', amount: 0.3, dur: 0.3 },
    { at: 9.0, actor: 'octopus', do: 'moveTo', to: { x: 136, y: 71.5 }, dur: 0.3 },
    { at: 9.25, actor: 'octopus', do: 'flash', dur: 0.6 },
    { at: 9.25, actor: 'octopus', do: 'hop', amount: 3, dur: 0.25 },
  ],
  builds: [
    // 吹上天的火苗掉下來 → 灬；被吹走的奶油 → 上面；拉炮的彩帶 → 米
    { at: 5.0, dur: 0.6, strokes: [12, 13, 14, 15], from: { x: 80, y: 30 }, style: 'drop', color: '#FF7A1A' },
    { at: 5.2, dur: 0.7, strokes: [6, 7, 8, 9, 10, 11], from: 'cake', color: '#EC407A' },
    { at: 5.6, dur: 0.7, strokes: [0, 1, 2, 3, 4, 5], from: 'popper', color: '#7E57C2' },
  ],
  glyph: [{ at: 6.3, dur: 0.4, do: 'wobble' }, { at: 9.5, dur: 0.5, do: 'pulse' }],
  fx: [
    { at: 0.6, kind: 'bubble', actor: 'pig', emoji: '🥳', dur: 0.7 },
    { at: 1.55, kind: 'burst', x: 80, y: 60, emoji: '💨', n: 4, dur: 0.4 },
    { at: 2.0, kind: 'burst', x: 80, y: 57, emoji: '✨', n: 5, dur: 0.4 },
    { at: 2.2, kind: 'pop', actor: 'pig', emoji: '😳', dur: 0.5 },
    { at: 3.2, kind: 'burst', x: 80, y: 60, emoji: '💨', n: 5, dur: 0.4 },
    { at: 3.6, kind: 'burst', x: 80, y: 57, emoji: '✨', n: 5, dur: 0.4 },
    { at: 3.75, kind: 'pop', actor: 'pig', emoji: '💢', dur: 0.5 },
    { at: 3.8, kind: 'pop', actor: 'octopus', emoji: '😆', dur: 0.6 },
    { at: 4.3, kind: 'sweat', actor: 'pig' },
    { at: 4.85, kind: 'burst', x: 80, y: 58, emoji: '🔥', n: 4, dur: 0.4 },
    { at: 5.6, kind: 'burst', actor: 'popper', emoji: '🎊', n: 6, dur: 0.6 },
    { at: 5.9, kind: 'dizzy', actor: 'pig', dur: 0.9 },
    { at: 6.95, kind: 'burst', actor: 'cake', emoji: '✨', n: 6, dur: 0.6 },
    { at: 7.4, kind: 'pop', actor: 'pig', emoji: '🤤', dur: 0.6 },
    { at: 8.05, kind: 'pop', actor: 'pig', emoji: '😑', dur: 0.6 },
    { at: 9.25, kind: 'pop', actor: 'octopus', emoji: '🔥', dur: 0.6 },
    { at: 9.3, kind: 'pop', actor: 'pig', emoji: '😱', dur: 0.7 },
  ],
  camera: [
    { at: 4.5, dur: 0.6, do: 'punch', amount: 0.2, to: { x: 40, y: 60 } },
    { at: 4.85, dur: 0.4, do: 'shake', amount: 1.5 },
  ],
  cues: [
    { at: 1.4, sfx: 'whoosh' },
    { at: 1.6, say: '糕' },
    { at: 2.0, sfx: 'blip' },
    { at: 3.05, sfx: 'whoosh' },
    { at: 3.6, sfx: 'blip' },
    { at: 4.75, sfx: 'whoosh' },
    { at: 4.85, sfx: 'deflate' },
    { at: 5.6, sfx: 'poof' },
    { at: 6.35, say: '糕' },
    { at: 7.3, say: '蛋糕' },
    { at: 8.0, sfx: 'blip' },
    { at: 8.85, sfx: 'gulp' },
    { at: 9.25, sfx: 'hic' },
    { at: 9.65, sfx: 'cheer' },
  ],
}

export default clip
