import type { Clip } from '../clip'

// 糖：小螞蟻找到一顆大糖果，推不動；叫來兩個朋友，還是推不動；吹號角叫來整支螞蟻大軍，終於扛起來走回家——結果糖果比洞口大，
// 塞到「喀」一聲碎成「糖」。天上下起糖果雨，大家好開心；隊長又推來一根更大的棒棒糖，整群螞蟻當場昏倒。糖、糖、糖果
const clip: Clip = {
  char: '糖',
  meta: { theme: '螞蟻大軍', cast: '螞蟻隊長＋螞蟻大軍＋糖果', gags: ['推不動', '叫越來越多人', '比洞口大塞不進去', '更大的來了全昏倒'] },
  duration: 10,
  bg: { top: '#FFF2E4', bottom: '#FFDDEB', floor: '#C99B6D', scenery: 'room' },
  actors: [
    { id: 'hole', emoji: '🕳️', x: 136, y: 75.5, size: 10 },
    { id: 'lolli', emoji: '🍭', x: 20, y: 67.8, size: 22, hidden: true },
    { id: 'a1', emoji: '🐜', x: 56, y: 74, size: 7, hidden: true, flip: true },
    { id: 'a2', emoji: '🐜', x: 56, y: 74, size: 7, hidden: true, flip: true },
    { id: 'a3', emoji: '🐜', x: 48, y: 74, size: 7, hidden: true, flip: true },
    { id: 'a4', emoji: '🐜', x: 40, y: 74, size: 7, hidden: true, flip: true },
    { id: 'a5', emoji: '🐜', x: 32, y: 74, size: 7, hidden: true, flip: true },
    { id: 'a6', emoji: '🐜', x: 24, y: 74, size: 7, hidden: true, flip: true },
    { id: 'a7', emoji: '🐜', x: 16, y: 74, size: 7, hidden: true, flip: true },
    { id: 'a8', emoji: '🐜', x: 8, y: 74, size: 7, hidden: true, flip: true },
    { id: 'candy', emoji: '🍬', x: 74, y: 71.1, size: 14 },
  ],
  moves: [
    { at: 0, actor: 'a1', do: 'enter', from: { x: -8, y: 74 }, dur: 0.6 },
    { at: 0.3, actor: 'candy', do: 'flash', dur: 0.6 },
    // 一隻推不動
    { at: 1.0, actor: 'a1', do: 'moveTo', to: { x: 64, y: 74 }, dur: 0.2 },
    { at: 1.2, actor: 'a1', do: 'squash', amount: -0.3, dur: 0.5 },
    // 三隻還是推不動
    { at: 2.1, actor: 'a2', do: 'enter', from: { x: -8, y: 74 }, dur: 0.4 },
    { at: 2.15, actor: 'a3', do: 'enter', from: { x: -8, y: 74 }, dur: 0.4 },
    { at: 2.6, actor: 'a1', do: 'squash', amount: -0.3, dur: 0.4 },
    { at: 2.6, actor: 'a2', do: 'squash', amount: -0.3, dur: 0.4 },
    { at: 2.6, actor: 'a3', do: 'squash', amount: -0.3, dur: 0.4 },
    { at: 2.6, actor: 'candy', do: 'shake', dur: 0.4, amount: 0.5 },
    // 螞蟻大軍
    { at: 3.1, actor: 'a4', do: 'enter', from: { x: -8, y: 74 }, dur: 0.5 },
    { at: 3.2, actor: 'a5', do: 'enter', from: { x: -8, y: 74 }, dur: 0.5 },
    { at: 3.3, actor: 'a6', do: 'enter', from: { x: -8, y: 74 }, dur: 0.5 },
    { at: 3.4, actor: 'a7', do: 'enter', from: { x: -8, y: 74 }, dur: 0.5 },
    { at: 3.5, actor: 'a8', do: 'enter', from: { x: -8, y: 74 }, dur: 0.5 },
    // 鑽到糖果底下，扛起來
    { at: 3.9, actor: 'a1', do: 'moveTo', to: { x: 44, y: 74 }, dur: 0.3 },
    { at: 3.9, actor: 'a2', do: 'moveTo', to: { x: 62, y: 74 }, dur: 0.3 },
    { at: 3.9, actor: 'a3', do: 'moveTo', to: { x: 66, y: 74 }, dur: 0.3 },
    { at: 3.9, actor: 'a4', do: 'moveTo', to: { x: 70, y: 74 }, dur: 0.3 },
    { at: 3.9, actor: 'a5', do: 'moveTo', to: { x: 74, y: 74 }, dur: 0.3 },
    { at: 3.9, actor: 'a6', do: 'moveTo', to: { x: 78, y: 74 }, dur: 0.3 },
    { at: 3.9, actor: 'a7', do: 'moveTo', to: { x: 82, y: 74 }, dur: 0.3 },
    { at: 3.9, actor: 'a8', do: 'moveTo', to: { x: 86, y: 74 }, dur: 0.3 },
    { at: 4.25, actor: 'candy', do: 'moveTo', to: { x: 74, y: 64 }, dur: 0.25 },
    { at: 4.3, actor: 'a1', do: 'bounce', dur: 0.4, times: 2, amount: 2 },
    // 扛回家
    { at: 4.6, actor: 'candy', do: 'moveTo', to: { x: 126, y: 64 }, dur: 0.8 },
    { at: 4.6, actor: 'a2', do: 'moveTo', to: { x: 114, y: 74 }, dur: 0.8 },
    { at: 4.6, actor: 'a3', do: 'moveTo', to: { x: 118, y: 74 }, dur: 0.8 },
    { at: 4.6, actor: 'a4', do: 'moveTo', to: { x: 122, y: 74 }, dur: 0.8 },
    { at: 4.6, actor: 'a5', do: 'moveTo', to: { x: 126, y: 74 }, dur: 0.8 },
    { at: 4.6, actor: 'a6', do: 'moveTo', to: { x: 130, y: 74 }, dur: 0.8 },
    { at: 4.6, actor: 'a7', do: 'moveTo', to: { x: 134, y: 74 }, dur: 0.8 },
    { at: 4.6, actor: 'a8', do: 'moveTo', to: { x: 138, y: 74 }, dur: 0.8 },
    { at: 4.6, actor: 'candy', do: 'bounce', dur: 0.8, times: 4, amount: 1 },
    // 塞不進洞口——喀！
    { at: 5.45, actor: 'candy', do: 'moveTo', to: { x: 136, y: 68 }, dur: 0.2 },
    { at: 5.6, actor: 'candy', do: 'squash', amount: 0.45, dur: 0.3 },
    { at: 5.6, actor: 'candy', do: 'shake', dur: 0.3, amount: 1 },
    { at: 5.9, actor: 'candy', do: 'vanish', dur: 0.15 },
    // 糖果雨
    { at: 7.7, actor: 'a3', do: 'hop', dur: 0.3, amount: 4 },
    { at: 7.8, actor: 'a5', do: 'hop', dur: 0.3, amount: 4 },
    { at: 7.9, actor: 'a7', do: 'hop', dur: 0.3, amount: 4 },
    // 回馬槍：隊長推來更大的棒棒糖，全部昏倒
    { at: 8.4, actor: 'lolli', do: 'enter', from: { x: -20, y: 67.8 }, dur: 0.6 },
    { at: 8.4, actor: 'a1', do: 'moveTo', to: { x: 36, y: 74 }, dur: 0.6 },
    { at: 9.1, actor: 'a2', do: 'rotateTo', amount: 180, dur: 0.25 },
    { at: 9.15, actor: 'a4', do: 'rotateTo', amount: 180, dur: 0.25 },
    { at: 9.2, actor: 'a6', do: 'rotateTo', amount: 180, dur: 0.25 },
    { at: 9.25, actor: 'a8', do: 'rotateTo', amount: 180, dur: 0.25 },
    { at: 9.3, actor: 'a3', do: 'rotateTo', amount: 180, dur: 0.25 },
    { at: 9.35, actor: 'a5', do: 'rotateTo', amount: 180, dur: 0.25 },
    { at: 9.4, actor: 'a7', do: 'rotateTo', amount: 180, dur: 0.25 },
  ],
  builds: [
    // 碎掉的糖果 → 米（粉紅）＋唐（紫）
    { at: 5.9, dur: 0.6, strokes: [0, 1, 2, 3, 4, 5], from: 'candy', color: '#FF4F98' },
    { at: 6.1, dur: 0.8, strokes: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15], from: 'candy', color: '#8C5BE0' },
  ],
  glyph: [{ at: 6.95, dur: 0.4, do: 'wobble' }, { at: 9.5, dur: 0.5, do: 'pulse' }],
  fx: [
    { at: 0.6, kind: 'bubble', actor: 'a1', emoji: '🤤', dur: 0.6 },
    { at: 1.8, kind: 'sweat', actor: 'a1' },
    { at: 1.95, kind: 'pop', actor: 'a1', emoji: '📣', dur: 0.4 },
    { at: 3.0, kind: 'bubble', actor: 'a1', emoji: '😩', dur: 0.5 },
    { at: 3.1, kind: 'pop', actor: 'a1', emoji: '📣', dur: 0.4, dx: 8 },
    { at: 4.0, kind: 'puff', actor: 'a5' },
    { at: 4.6, kind: 'puff', actor: 'a5' },
    { at: 5.6, kind: 'sweat', actor: 'a8' },
    { at: 5.9, kind: 'burst', actor: 'candy', emoji: '✨', n: 8, dur: 0.6 },
    { at: 6.2, kind: 'pop', actor: 'a5', emoji: '😮', dur: 0.6 },
    { at: 7.5, kind: 'rain', x: 126, y: 38, emoji: '🍬', n: 7, dur: 1.0 },
    { at: 8.0, kind: 'pop', actor: 'a6', emoji: '😋', dur: 0.6 },
    { at: 8.6, kind: 'pop', actor: 'a1', emoji: '📣', dur: 0.5 },
    { at: 9.2, kind: 'pop', actor: 'a5', emoji: '😵', dur: 0.7 },
  ],
  camera: [
    { at: 5.6, dur: 0.6, do: 'punch', amount: 0.3, to: { x: 132, y: 66 } },
    { at: 5.9, dur: 0.3, do: 'shake', amount: 1.2 },
  ],
  cues: [
    { at: 0.3, sfx: 'blip' },
    { at: 1.3, say: '糖' },
    { at: 1.95, sfx: 'blip' },
    { at: 2.6, sfx: 'tap' },
    { at: 3.1, sfx: 'blip' },
    { at: 3.2, sfx: 'rumble' },
    { at: 4.25, sfx: 'boing' },
    { at: 4.6, sfx: 'tap' }, { at: 4.8, sfx: 'tap' }, { at: 5.0, sfx: 'tap' }, { at: 5.2, sfx: 'tap' },
    { at: 5.6, sfx: 'bonk' },
    { at: 5.9, sfx: 'crack' },
    { at: 6.95, say: '糖' },
    { at: 7.6, sfx: 'plop' },
    { at: 7.95, say: '糖果' },
    { at: 8.6, sfx: 'blip' },
    { at: 9.1, sfx: 'plop' },
    { at: 9.6, sfx: 'cheer' },
  ],
}

export default clip
