import type { Clip } from '../clip'

// 蜂：熊指揮家帶三隻蜜蜂開晚會，揮慢慢的好聽，越揮越快蜜蜂就亂飛，指揮棒還甩飛了——蜜蜂全部掉頭追著熊跑！
// 熊衝去猛敲大鼓「咚」，蜜蜂嚇得把音符抖成「蜂」。熊拿蜂蜜犒賞；結果小瓢蟲撿回指揮棒，輕輕一揮蜜蜂就乖乖整齊演奏。蜂、蜂、蜜蜂
const clip: Clip = {
  char: '蜂',
  meta: { theme: '蜜蜂音樂會', cast: '熊指揮家＋三隻蜜蜂＋瓢蟲', gags: ['越揮越快失控', '指揮棒甩飛', '被樂團追著跑', '小瓢蟲指揮得比較好'] },
  duration: 10,
  bg: { top: '#1E2352', bottom: '#433F86', floor: '#3E5E3A', scenery: 'night' },
  actors: [
    { id: 'drum', emoji: '🥁', x: 128, y: 72.8, size: 10, hidden: true },
    { id: 'honey', emoji: '🍯', x: 148, y: 72.4, size: 11, hidden: true },
    { id: 'bear', emoji: '🐻', x: 24, y: 71.1, size: 14, hidden: true },
    { id: 'lady', emoji: '🐞', x: 40, y: 74.5, size: 6, hidden: true },
    { id: 'baton', emoji: '🪄', x: 35, y: 58, size: 7, hidden: true, float: true },
    { id: 'b1', emoji: '🐝', x: 100, y: 42, size: 9, hidden: true, float: true },
    { id: 'b2', emoji: '🐝', x: 120, y: 32, size: 9, hidden: true, float: true },
    { id: 'b3', emoji: '🐝', x: 140, y: 42, size: 9, hidden: true, float: true },
  ],
  moves: [
    { at: 0, actor: 'bear', do: 'pop' },
    { at: 0.1, actor: 'drum', do: 'pop' },
    { at: 0.2, actor: 'b1', do: 'pop' }, { at: 0.3, actor: 'b2', do: 'pop' }, { at: 0.4, actor: 'b3', do: 'pop' },
    { at: 0.5, actor: 'baton', do: 'pop' },
    // 慢慢揮：好聽
    { at: 0.9, actor: 'baton', do: 'tilt', amount: -35, dur: 0.35 },
    { at: 0.9, actor: 'bear', do: 'hop', amount: 3, dur: 0.3 },
    { at: 1.3, actor: 'baton', do: 'tilt', amount: 35, dur: 0.4 },
    { at: 1.3, actor: 'b1', do: 'bounce', amount: 2, times: 2, dur: 0.8 },
    { at: 1.3, actor: 'b2', do: 'bounce', amount: 2, times: 2, dur: 0.8 },
    { at: 1.3, actor: 'b3', do: 'bounce', amount: 2, times: 2, dur: 0.8 },
    { at: 2.0, actor: 'baton', do: 'tilt', amount: 35, dur: 0.35 },
    // 越揮越快：蜜蜂亂飛
    { at: 2.5, actor: 'baton', do: 'spin', times: 2, dur: 0.4 },
    { at: 2.5, actor: 'bear', do: 'shake', amount: 1, dur: 0.5 },
    { at: 2.5, actor: 'b1', do: 'moveTo', to: { x: 84, y: 24 }, dur: 0.3 },
    { at: 2.5, actor: 'b2', do: 'moveTo', to: { x: 146, y: 60 }, dur: 0.3 },
    { at: 2.5, actor: 'b3', do: 'moveTo', to: { x: 112, y: 58 }, dur: 0.3 },
    { at: 2.85, actor: 'b1', do: 'moveTo', to: { x: 118, y: 56 }, dur: 0.3 },
    { at: 2.85, actor: 'b2', do: 'moveTo', to: { x: 96, y: 26 }, dur: 0.3 },
    { at: 2.85, actor: 'b3', do: 'moveTo', to: { x: 148, y: 26 }, dur: 0.3 },
    { at: 3.2, actor: 'baton', do: 'spin', times: 4, dur: 0.3 },
    { at: 3.2, actor: 'b1', do: 'moveTo', to: { x: 90, y: 44 }, dur: 0.3 },
    { at: 3.2, actor: 'b2', do: 'moveTo', to: { x: 130, y: 40 }, dur: 0.3 },
    { at: 3.2, actor: 'b3', do: 'moveTo', to: { x: 104, y: 30 }, dur: 0.3 },
    // 指揮棒甩飛了
    { at: 3.5, actor: 'baton', do: 'moveTo', to: { x: -15, y: 12 }, arc: 12, dur: 0.5 },
    { at: 3.5, actor: 'baton', do: 'spin', times: 3, dur: 0.5 },
    // 蜜蜂掉頭追熊
    { at: 3.85, actor: 'b1', do: 'moveTo', to: { x: 38, y: 58 }, dur: 0.35 },
    { at: 3.85, actor: 'b2', do: 'moveTo', to: { x: 28, y: 53 }, dur: 0.35 },
    { at: 3.85, actor: 'b3', do: 'moveTo', to: { x: 16, y: 58 }, dur: 0.35 },
    { at: 4.15, actor: 'bear', do: 'squash', amount: -0.25, dur: 0.15 },
    { at: 4.25, actor: 'bear', do: 'moveTo', to: { x: 114, y: 71.1 }, dur: 0.5 },
    { at: 4.35, actor: 'b1', do: 'moveTo', to: { x: 100, y: 58 }, dur: 0.5 },
    { at: 4.35, actor: 'b2', do: 'moveTo', to: { x: 90, y: 52 }, dur: 0.5 },
    { at: 4.35, actor: 'b3', do: 'moveTo', to: { x: 80, y: 58 }, dur: 0.5 },
    // 咚！猛敲大鼓
    { at: 4.75, actor: 'bear', do: 'hop', amount: 6, dur: 0.25 },
    { at: 4.95, actor: 'drum', do: 'squash', amount: 0.5, dur: 0.3 },
    { at: 4.95, actor: 'b1', do: 'shake', amount: 1.5, dur: 0.3 },
    { at: 4.95, actor: 'b2', do: 'shake', amount: 1.5, dur: 0.3 },
    { at: 4.95, actor: 'b3', do: 'shake', amount: 1.5, dur: 0.3 },
    // 音符抖出去後，蜜蜂飛到右上角
    { at: 5.3, actor: 'b1', do: 'moveTo', to: { x: 130, y: 26 }, dur: 0.4 },
    { at: 5.7, actor: 'b2', do: 'moveTo', to: { x: 148, y: 34 }, dur: 0.4 },
    { at: 6.05, actor: 'b3', do: 'moveTo', to: { x: 134, y: 44 }, dur: 0.4 },
    // 蜂蜜犒賞
    { at: 6.9, actor: 'honey', do: 'pop' },
    { at: 7.1, actor: 'b1', do: 'moveTo', to: { x: 138, y: 60 }, dur: 0.4 },
    { at: 7.1, actor: 'b2', do: 'moveTo', to: { x: 156, y: 58 }, dur: 0.4 },
    { at: 7.1, actor: 'b3', do: 'moveTo', to: { x: 147, y: 53 }, dur: 0.4 },
    { at: 7.5, actor: 'b1', do: 'bounce', amount: 2, times: 3, dur: 0.6 },
    { at: 7.5, actor: 'b2', do: 'bounce', amount: 2, times: 3, dur: 0.6 },
    { at: 7.5, actor: 'b3', do: 'bounce', amount: 2, times: 3, dur: 0.6 },
    // 小瓢蟲撿回指揮棒
    { at: 7.9, actor: 'baton', do: 'moveTo', to: { x: -10, y: 67 }, dur: 0.05 },
    { at: 8.0, actor: 'lady', do: 'enter', from: { x: -10, y: 74.5 }, dur: 0.6 },
    { at: 8.0, actor: 'baton', do: 'moveTo', to: { x: 45, y: 67 }, dur: 0.6 },
    { at: 8.7, actor: 'baton', do: 'tilt', amount: -30, dur: 0.3 },
    { at: 9.0, actor: 'baton', do: 'tilt', amount: 30, dur: 0.3 },
    { at: 8.7, actor: 'b1', do: 'bounce', amount: 3, times: 3, dur: 0.9 },
    { at: 8.7, actor: 'b2', do: 'bounce', amount: 3, times: 3, dur: 0.9 },
    { at: 8.7, actor: 'b3', do: 'bounce', amount: 3, times: 3, dur: 0.9 },
    { at: 9.1, actor: 'bear', do: 'squash', amount: 0.3, dur: 0.4 },
    { at: 9.4, actor: 'lady', do: 'squash', amount: 0.4, dur: 0.4 },
  ],
  builds: [
    // 嚇出來的音符 → 虫、夂、丰
    { at: 5.1, dur: 0.7, strokes: [0, 1, 2, 3, 4, 5], from: 'b1', color: '#FFC93C' },
    { at: 5.5, dur: 0.5, strokes: [6, 7, 8], from: 'b2', color: '#FF8A3D' },
    { at: 5.85, dur: 0.55, strokes: [9, 10, 11, 12], from: 'b3', color: '#8FE3FF' },
  ],
  glyph: [{ at: 6.4, dur: 0.4, do: 'wobble' }, { at: 9.5, dur: 0.5, do: 'pulse' }],
  fx: [
    { at: 0.5, kind: 'bubble', actor: 'bear', emoji: '🎼', dur: 0.7 },
    { at: 1.3, kind: 'zzz', actor: 'b1', emoji: '🎵', dur: 1.2 },
    { at: 1.35, kind: 'zzz', actor: 'b2', emoji: '🎶', dur: 1.2 },
    { at: 1.4, kind: 'zzz', actor: 'b3', emoji: '🎵', dur: 1.2 },
    { at: 2.6, kind: 'sweat', actor: 'bear' },
    { at: 2.9, kind: 'burst', actor: 'b2', emoji: '🎵', n: 6, dur: 0.5 },
    { at: 3.6, kind: 'pop', actor: 'bear', emoji: '😳', dur: 0.5 },
    { at: 3.9, kind: 'pop', actor: 'b1', emoji: '💢', dur: 0.4 },
    { at: 4.25, kind: 'puff', actor: 'bear' },
    { at: 4.95, kind: 'burst', actor: 'drum', dur: 0.4 },
    { at: 4.95, kind: 'burst', actor: 'drum', emoji: '🎵', n: 8, dur: 0.6 },
    { at: 6.9, kind: 'burst', actor: 'honey', emoji: '✨', n: 5, dur: 0.4, dx: -8 },
    { at: 7.35, kind: 'burst', actor: 'honey', emoji: '💕', n: 5, dur: 0.6, dx: -8 },
    { at: 7.6, kind: 'bubble', actor: 'bear', emoji: '🤤', dur: 0.7 },
    { at: 8.7, kind: 'zzz', actor: 'b1', emoji: '🎵', dur: 1.2 },
    { at: 8.75, kind: 'zzz', actor: 'b3', emoji: '🎶', dur: 1.2 },
    { at: 8.95, kind: 'pop', actor: 'bear', emoji: '😮', dur: 0.5 },
    { at: 9.45, kind: 'bubble', actor: 'bear', emoji: '😑', dur: 0.55 },
  ],
  camera: [
    { at: 3.6, dur: 0.5, do: 'punch', amount: 0.25, to: { x: 26, y: 62 } },
    { at: 4.95, dur: 0.4, do: 'shake', amount: 2 },
  ],
  cues: [
    { at: 0.9, sfx: 'tap' },
    { at: 1.4, say: '蜂' },
    { at: 2.5, sfx: 'whoosh' }, { at: 2.85, sfx: 'whoosh' },
    { at: 3.5, sfx: 'whoosh' },
    { at: 3.85, sfx: 'boing' },
    { at: 4.25, sfx: 'whoosh' },
    { at: 4.95, sfx: 'bonk' }, { at: 4.95, sfx: 'rumble' },
    { at: 6.4, say: '蜂' },
    { at: 6.9, sfx: 'plop' },
    { at: 7.4, say: '蜜蜂' },
    { at: 8.7, sfx: 'tap' },
    { at: 9.6, sfx: 'cheer' },
  ],
}

export default clip
