import type { Clip } from '../clip'
import { pressStack } from '../helpers'

// 頭：小狗頭上被一樣一樣東西疊上去（帽子、漢堡、貓、蛋糕），最後一顆西瓜壓下來，全部飛出去變成字。
// 牠趕快戴上頭盔，西瓜再砸下來「啵」一聲彈走，好帥；一脫掉頭盔，一顆小櫻桃就把牠砸扁。頭、頭、頭盔
const clip: Clip = {
  char: '頭',
  meta: { theme: '動物', cast: '小狗＋貓', gags: ['疊疊樂', '壓扁', '學乖反轉', '東西砸頭', '回馬槍'] },
  duration: 10,
  bg: { top: '#E3F4FF', bottom: '#CDE9FB', floor: '#F7E3B5', scenery: 'city' },
  actors: [
    { id: 'dog', emoji: '🐶', x: 30, y: 71, size: 14, hidden: true },
    { id: 'hat', emoji: '🎩', x: 30, y: 60, size: 8, hidden: true },
    { id: 'burger', emoji: '🍔', x: 30, y: 53, size: 8, hidden: true },
    { id: 'cat', emoji: '🐱', x: 30, y: 45.5, size: 8, hidden: true },
    { id: 'cake', emoji: '🎂', x: 30, y: 38, size: 8, hidden: true },
    { id: 'melon', emoji: '🍉', x: 30, y: 29, size: 11, hidden: true },
    { id: 'helmet', emoji: '⛑️', x: 30, y: 60, size: 9, hidden: true },
    { id: 'melon2', emoji: '🍉', x: 30, y: 53, size: 11, hidden: true },
    { id: 'cherry', emoji: '🍒', x: 30, y: 61, size: 5, hidden: true },
  ],
  moves: [
    { at: 0, actor: 'dog', do: 'enter', dur: 0.7 },
    { at: 0, actor: 'dog', do: 'bounce', dur: 0.7, times: 3, amount: 2 },
    // 一樣一樣疊上來，每疊一樣就被壓一下
    { at: 0.9, actor: 'hat', do: 'enter', from: { x: 30, y: -10 }, dur: 0.4 },
    { at: 1.3, actor: 'dog', do: 'squash', amount: 0.2, dur: 0.2 },
    ...pressStack(1.3, 0.2, 0.2, 14, ['hat']),
    { at: 1.5, actor: 'dog', do: 'hop', dur: 0.3, amount: 2 },
    { at: 1.7, actor: 'burger', do: 'enter', from: { x: 30, y: -10 }, dur: 0.4 },
    { at: 2.1, actor: 'dog', do: 'squash', amount: 0.25, dur: 0.2 },
    ...pressStack(2.1, 0.2, 0.25, 14, ['hat', 'burger']),
    { at: 2.4, actor: 'cat', do: 'enter', from: { x: 30, y: -10 }, dur: 0.4 },
    { at: 2.8, actor: 'dog', do: 'squash', amount: 0.3, dur: 0.2 },
    ...pressStack(2.8, 0.2, 0.3, 14, ['hat', 'burger', 'cat']),
    { at: 2.85, actor: 'cat', do: 'hop', dur: 0.25, amount: 2 },
    { at: 3.1, actor: 'cake', do: 'enter', from: { x: 30, y: -10 }, dur: 0.4 },
    { at: 3.5, actor: 'dog', do: 'squash', amount: 0.35, dur: 0.2 },
    ...pressStack(3.5, 0.2, 0.35, 14, ['hat', 'burger', 'cat', 'cake']),
    // 搖搖晃晃，越上面晃越大
    { at: 3.5, actor: 'hat', do: 'shake', dur: 0.9, amount: 0.4 },
    { at: 3.5, actor: 'burger', do: 'shake', dur: 0.9, amount: 0.8 },
    { at: 3.5, actor: 'cat', do: 'shake', dur: 0.9, amount: 1.2 },
    { at: 3.5, actor: 'cake', do: 'shake', dur: 0.9, amount: 1.6 },
    // 西瓜！
    { at: 3.9, actor: 'melon', do: 'enter', from: { x: 30, y: -14 }, dur: 0.35 },
    { at: 4.25, actor: 'dog', do: 'squash', amount: 0.55, dur: 0.4 },
    ...pressStack(4.25, 0.4, 0.55, 14, ['hat', 'burger', 'cat', 'cake', 'melon']),
    { at: 4.3, actor: 'hat', do: 'shake', dur: 0.6, amount: 0.8 },
    { at: 4.3, actor: 'burger', do: 'shake', dur: 0.6, amount: 1.6 },
    { at: 4.3, actor: 'cat', do: 'shake', dur: 0.6, amount: 2.4 },
    { at: 4.3, actor: 'cake', do: 'shake', dur: 0.6, amount: 3.2 },
    { at: 4.3, actor: 'melon', do: 'shake', dur: 0.6, amount: 4 },
    // 全部飛出去
    { at: 4.9, actor: 'hat', do: 'moveTo', to: { x: 58, y: 20 }, dur: 0.4, arc: 10 },
    { at: 4.9, actor: 'burger', do: 'moveTo', to: { x: 66, y: 34 }, dur: 0.4, arc: 12 },
    { at: 4.9, actor: 'cat', do: 'moveTo', to: { x: 140, y: 71 }, dur: 0.7, arc: 30 },
    { at: 4.9, actor: 'cat', do: 'spin', dur: 0.7, times: 2 },
    { at: 4.9, actor: 'cake', do: 'moveTo', to: { x: 92, y: 24 }, dur: 0.4, arc: 14 },
    { at: 4.9, actor: 'melon', do: 'moveTo', to: { x: 98, y: 46 }, dur: 0.4, arc: 10 },
    { at: 4.9, actor: 'hat', do: 'spin', dur: 0.4 }, { at: 4.9, actor: 'burger', do: 'spin', dur: 0.4 },
    { at: 4.9, actor: 'cake', do: 'spin', dur: 0.4 }, { at: 4.9, actor: 'melon', do: 'spin', dur: 0.4 },
    { at: 5.3, actor: 'hat', do: 'vanish' }, { at: 5.3, actor: 'burger', do: 'vanish' },
    { at: 5.3, actor: 'cake', do: 'vanish' }, { at: 5.3, actor: 'melon', do: 'vanish' },
    { at: 5.6, actor: 'cat', do: 'squash', amount: 0.3, dur: 0.25 },
    // 學乖了：戴頭盔
    { at: 6.8, actor: 'helmet', do: 'enter', from: { x: 30, y: -10 }, dur: 0.3 },
    { at: 7.1, actor: 'dog', do: 'squash', amount: 0.2, dur: 0.15 },
    ...pressStack(7.1, 0.15, 0.2, 14, ['helmet']),
    { at: 7.4, actor: 'melon2', do: 'enter', from: { x: 30, y: -14 }, dur: 0.3 },
    { at: 7.7, actor: 'melon2', do: 'moveTo', to: { x: -10, y: 40 }, dur: 0.6, arc: 22 },
    { at: 7.7, actor: 'melon2', do: 'spin', dur: 0.6 },
    { at: 7.7, actor: 'helmet', do: 'squash', amount: 0.3, dur: 0.2 },
    { at: 7.7, actor: 'dog', do: 'squash', amount: 0.25, dur: 0.2 },
    ...pressStack(7.7, 0.2, 0.25, 14, ['helmet']),
    { at: 8.0, actor: 'dog', do: 'hop', dur: 0.3, amount: 3 },
    { at: 8.5, actor: 'helmet', do: 'moveTo', to: { x: 16, y: 72 }, dur: 0.3, arc: 6 },
    // 一脫掉……
    { at: 8.9, actor: 'cherry', do: 'enter', from: { x: 30, y: -10 }, dur: 0.3 },
    { at: 9.2, actor: 'dog', do: 'squash', amount: 0.6, dur: 0.4 },
    { at: 9.25, actor: 'cherry', do: 'moveTo', to: { x: 40, y: 73 }, dur: 0.35, arc: 6 },
  ],
  builds: [
    { at: 5.0, dur: 0.9, strokes: [0, 1, 2, 3, 4, 5, 6], from: { x: 62, y: 28 }, color: '#E8762D' },
    { at: 5.3, dur: 1.0, strokes: [7, 8, 9, 10, 11, 12, 13, 14, 15], from: { x: 95, y: 34 }, color: '#7A4FD8' },
  ],
  glyph: [{ at: 6.35, dur: 0.5, do: 'wobble' }, { at: 9.5, dur: 0.5, do: 'pulse' }],
  fx: [
    { at: 1.5, kind: 'pop', actor: 'dog', emoji: '✨', dur: 0.5, dy: 4 },
    { at: 3.4, kind: 'sweat', actor: 'dog', dy: 8 },
    { at: 4.25, kind: 'burst', actor: 'dog', dy: 6 },
    { at: 5.0, kind: 'dizzy', actor: 'dog', dur: 1.5 },
    { at: 5.6, kind: 'bubble', actor: 'cat', emoji: '😾', dur: 0.9 },
    { at: 6.5, kind: 'pop', actor: 'dog', emoji: '💡', dur: 0.5 },
    { at: 7.7, kind: 'burst', actor: 'helmet', emoji: '✨', n: 5, dur: 0.5 },
    { at: 8.0, kind: 'bubble', actor: 'dog', emoji: '😎', dur: 0.6 },
    { at: 9.2, kind: 'burst', actor: 'dog' },
    { at: 9.3, kind: 'bubble', actor: 'dog', emoji: '😵', dur: 0.7 },
  ],
  camera: [
    { at: 4.25, dur: 0.4, do: 'shake', amount: 1.5 },
    { at: 7.7, dur: 0.8, do: 'punch', amount: 0.25, to: { x: 30, y: 55 } },
    { at: 9.2, dur: 0.7, do: 'punch', amount: 0.35, to: { x: 30, y: 62 } },
  ],
  cues: [
    { at: 1.3, sfx: 'plop' },
    { at: 1.35, say: '頭' },
    { at: 2.1, sfx: 'plop' }, { at: 2.8, sfx: 'plop' }, { at: 3.5, sfx: 'plop' },
    { at: 4.25, sfx: 'bonk' },
    { at: 4.9, sfx: 'whoosh' },
    { at: 5.9, say: '頭' },
    { at: 6.5, sfx: 'blip' },
    { at: 7.1, say: '頭盔' },
    { at: 7.7, sfx: 'boing' },
    { at: 9.2, sfx: 'bonk' },
    { at: 9.6, sfx: 'cheer' },
  ],
}

export default clip
