import type { Clip } from '../clip'

// 鴨：河馬泡澡，捏一下浴缸裡的小黃鴨「啾」——捏一次多一隻，越捏越多，整缸塞滿小鴨，河馬被擠飛出浴缸。小鴨飛成「鴨」。
// 最後一隻真的鴨子走過來，河馬好奇捏一下——牠也「啾」一聲噴出一圈小黃鴨，河馬嚇倒。鴨、鴨、小鴨
const clip: Clip = {
  char: '鴨',
  meta: { theme: '浴室泡澡', cast: '河馬＋小黃鴨大軍＋真的鴨子', gags: ['捏一下多一隻', '失控塞滿浴缸', '被擠飛', '真鴨子也會啾'] },
  duration: 10,
  bg: { top: '#E2F6FB', bottom: '#C6EBF4', floor: '#F4F1EA', scenery: 'room' },
  actors: [
    { id: 'hippo', emoji: '🦛', x: 12, y: 70.3, size: 16, hidden: true, flip: true },
    { id: 'tub', emoji: '🛁', x: 30, y: 65.2, size: 28, hidden: true },
    { id: 'd1', emoji: '🐤', x: 38, y: 57, size: 6, hidden: true, float: true },
    { id: 'd2', emoji: '🐤', x: 21, y: 56, size: 6, hidden: true, float: true },
    { id: 'd3', emoji: '🐤', x: 44, y: 55, size: 6, hidden: true, float: true },
    { id: 'd4', emoji: '🐤', x: 29, y: 47, size: 6, hidden: true, float: true },
    { id: 'd5', emoji: '🐤', x: 10, y: 74.5, size: 6, hidden: true },
    { id: 'd6', emoji: '🐤', x: 48, y: 74.5, size: 6, hidden: true },
    { id: 'd7', emoji: '🐤', x: 4, y: 74.5, size: 6, hidden: true },
    { id: 'd8', emoji: '🐤', x: 29, y: 41.5, size: 6, hidden: true, float: true },
    { id: 'duck', emoji: '🦆', x: 151, y: 72, size: 12, hidden: true },
  ],
  moves: [
    { at: 0, actor: 'tub', do: 'pop' },
    { at: 0.1, actor: 'd1', do: 'pop' },
    { at: 0.1, actor: 'hippo', do: 'enter', from: { x: -15, y: 70.3 }, dur: 0.6 },
    { at: 0.8, actor: 'd1', do: 'bounce', dur: 0.8, times: 2, amount: 1 },
    // 跳進浴缸：水花，小鴨被噴上天
    { at: 1.1, actor: 'hippo', do: 'squash', amount: -0.3, dur: 0.2 },
    { at: 1.25, actor: 'hippo', do: 'moveTo', to: { x: 30, y: 58 }, dur: 0.45, arc: 14 },
    { at: 1.7, actor: 'd1', do: 'hop', dur: 0.6, amount: 18 },
    { at: 1.7, actor: 'd1', do: 'spin', dur: 0.6 },
    // 捏一下就多一隻，越捏越快
    { at: 2.4, actor: 'hippo', do: 'tilt', amount: 12, dur: 0.25 },
    { at: 2.4, actor: 'd1', do: 'squash', amount: 0.5, dur: 0.25 },
    { at: 2.45, actor: 'd2', do: 'pop' },
    { at: 2.9, actor: 'hippo', do: 'tilt', amount: 12, dur: 0.25 },
    { at: 2.9, actor: 'd1', do: 'squash', amount: 0.5, dur: 0.25 },
    { at: 2.95, actor: 'd3', do: 'pop' },
    { at: 3.3, actor: 'hippo', do: 'tilt', amount: 12, dur: 0.2 },
    { at: 3.3, actor: 'd1', do: 'squash', amount: 0.5, dur: 0.2 },
    { at: 3.35, actor: 'd4', do: 'pop' },
    { at: 3.6, actor: 'd5', do: 'pop', dur: 0.25 },
    { at: 3.7, actor: 'd6', do: 'pop', dur: 0.25 },
    { at: 3.8, actor: 'd7', do: 'pop', dur: 0.25 },
    { at: 3.9, actor: 'd8', do: 'pop', dur: 0.25 },
    ...['d1', 'd2', 'd3', 'd4', 'd8'].map((actor) => ({ at: 4.1, actor, do: 'bounce' as const, dur: 0.4, times: 2, amount: 2 })),
    // 河馬被擠飛出去，落在右邊
    { at: 4.2, actor: 'hippo', do: 'moveTo', to: { x: 134, y: 70.3 }, dur: 0.8, arc: 38 },
    { at: 4.2, actor: 'hippo', do: 'spin', dur: 0.8 },
    { at: 5.0, actor: 'hippo', do: 'squash', amount: 0.35, dur: 0.3 },
    ...['d2', 'd3', 'd4', 'd5', 'd6', 'd7', 'd8'].map((actor, i) => ({ at: 4.6 + i * 0.07, actor, do: 'vanish' as const, dur: 0.3 })),
    { at: 6.9, actor: 'd1', do: 'hop', dur: 0.5, amount: 6 },
    { at: 7.0, actor: 'd1', do: 'squash', amount: 0.4, dur: 0.25 },
    // 真的鴨子走來，河馬捏一下
    { at: 7.9, actor: 'duck', do: 'enter', from: { x: 175, y: 72 }, dur: 0.6 },
    { at: 8.5, actor: 'hippo', do: 'moveTo', to: { x: 138, y: 70.3 }, dur: 0.15 },
    { at: 8.6, actor: 'duck', do: 'squash', amount: 0.45, dur: 0.25 },
    { at: 8.95, actor: 'hippo', do: 'rotateTo', amount: -90, dur: 0.3 },
    { at: 8.95, actor: 'hippo', do: 'moveTo', to: { x: 128, y: 70.3 }, dur: 0.3 },
  ],
  builds: [
    // 一缸小鴨飛出去：甲、鳥
    { at: 4.6, dur: 0.6, strokes: [0, 1, 2, 3, 4], from: 'd4', color: '#E8890C' },
    { at: 5.1, dur: 1.0, strokes: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15], from: { x: 22, y: 56 }, color: '#2C7DA0' },
  ],
  glyph: [{ at: 6.1, dur: 0.4, do: 'wobble' }, { at: 9.5, dur: 0.5, do: 'pulse' }],
  fx: [
    { at: 0.7, kind: 'bubble', actor: 'hippo', emoji: '🐤', dur: 0.8 },
    { at: 1.7, kind: 'fountain', actor: 'tub', dy: 6, n: 8, dur: 0.8 },
    { at: 2.45, kind: 'pop', actor: 'd1', emoji: '❗', dur: 0.4 },
    { at: 3.4, kind: 'pop', actor: 'hippo', emoji: '😳', dur: 0.5 },
    { at: 3.8, kind: 'sweat', actor: 'hippo' },
    { at: 4.15, kind: 'burst', actor: 'tub', emoji: '💦', n: 6, dur: 0.5, dy: 6 },
    { at: 4.6, kind: 'burst', actor: 'tub', emoji: '🐤', n: 6, dur: 0.5, dy: 4 },
    { at: 5.0, kind: 'puff', actor: 'hippo' },
    { at: 5.1, kind: 'dizzy', actor: 'hippo', dur: 1.0 },
    { at: 7.0, kind: 'pop', actor: 'd1', emoji: '💕', dur: 0.6 },
    { at: 8.3, kind: 'bubble', actor: 'hippo', emoji: '🤔', dur: 0.5, dx: -6 },
    { at: 8.65, kind: 'burst', actor: 'duck', emoji: '🐤', n: 6, dur: 0.6, dx: -12 },
    { at: 8.75, kind: 'pop', actor: 'hippo', emoji: '😱', dur: 0.6, dx: -10 },
    { at: 9.3, kind: 'dizzy', actor: 'hippo', dur: 0.7, dx: -8, dy: 6 },
  ],
  camera: [
    { at: 3.7, dur: 0.6, do: 'punch', amount: 0.25, to: { x: 30, y: 56 } },
    { at: 5.0, dur: 0.3, do: 'shake', amount: 1.5 },
  ],
  cues: [
    { at: 1.7, sfx: 'splash' },
    { at: 1.9, say: '鴨' },
    { at: 2.4, sfx: 'blip' },
    { at: 2.9, sfx: 'blip' },
    { at: 3.3, sfx: 'blip' },
    { at: 3.6, sfx: 'blip' }, { at: 3.7, sfx: 'blip' }, { at: 3.8, sfx: 'blip' }, { at: 3.9, sfx: 'blip' },
    { at: 4.2, sfx: 'boing' },
    { at: 5.0, sfx: 'bonk' },
    { at: 6.2, say: '鴨' },
    { at: 7.0, sfx: 'blip' },
    { at: 7.2, say: '小鴨' },
    { at: 8.6, sfx: 'blip' },
    { at: 8.65, sfx: 'poof' },
    { at: 9.0, sfx: 'bonk' },
    { at: 9.6, sfx: 'cheer' },
  ],
}

export default clip
